// ui_kits/wallet/DepositPanel.jsx
const depositPanelStyles = {
  wrap: {
    background: '#fff', borderRadius: 20,
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    padding: '24px 24px 22px',
    display: 'flex', flexDirection: 'column', gap: 14,
  },
  head: { display: 'flex', alignItems: 'baseline', gap: 10 },
  title: { fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 600, letterSpacing: '-0.01em' },
  sub: { fontSize: 12, color: 'var(--fg3)' },

  qrRow: { display: 'flex', gap: 18, alignItems: 'center' },
  qr: {
    width: 124, height: 124, borderRadius: 16,
    background: '#fff',
    boxShadow: 'inset 0 0 0 1px var(--hairline)',
    padding: 8,
    flexShrink: 0,
  },
  addressBox: {
    flex: 1, display: 'flex', flexDirection: 'column', gap: 10,
  },
  addressLbl: { fontSize: 12, fontWeight: 600, color: 'var(--fg2)' },
  addressField: {
    display: 'flex', alignItems: 'center', gap: 8,
    background: 'var(--bg-elevated)',
    borderRadius: 10, padding: '8px 8px 8px 14px',
  },
  addressVal: {
    flex: 1, fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--fg1)',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  copyBtn: {
    height: 30, padding: '0 12px', borderRadius: 8,
    background: '#fff', border: 0,
    fontSize: 12, fontWeight: 600, color: 'var(--fg1)',
    cursor: 'pointer', fontFamily: 'inherit',
    display: 'inline-flex', alignItems: 'center', gap: 6,
    boxShadow: '0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)',
  },

  notice: {
    display: 'flex', gap: 10, padding: '10px 12px',
    background: 'var(--accent-bg)', color: 'var(--accent-press)',
    fontSize: 12, lineHeight: 1.45, borderRadius: 10,
  },
};

/* Pure CSS / SVG mock QR — pattern is deterministic-looking, doesn't decode */
function FakeQR() {
  const cells = 21;
  // deterministic pseudo pattern
  const pattern = [];
  for (let r = 0; r < cells; r++) {
    for (let c = 0; c < cells; c++) {
      const corner = (r < 7 && c < 7) || (r < 7 && c >= cells - 7) || (r >= cells - 7 && c < 7);
      const v = ((r * 7 + c * 13 + r * c) % 5) < 2;
      pattern.push({ r, c, on: corner || v });
    }
  }
  const FINDER = (cx, cy) => (
    <g key={`f${cx},${cy}`}>
      <rect x={cx} y={cy} width="7" height="7" fill="#1D1D1F"/>
      <rect x={cx+1} y={cy+1} width="5" height="5" fill="#fff"/>
      <rect x={cx+2} y={cy+2} width="3" height="3" fill="#1D1D1F"/>
    </g>
  );
  return (
    <svg viewBox="0 0 21 21" width="100%" height="100%" shapeRendering="crispEdges">
      {pattern.filter(p => {
        const inFinder = (p.r < 7 && p.c < 7) || (p.r < 7 && p.c >= 14) || (p.r >= 14 && p.c < 7);
        return p.on && !inFinder;
      }).map(p => <rect key={`${p.r},${p.c}`} x={p.c} y={p.r} width="1" height="1" fill="#1D1D1F"/>)}
      {FINDER(0, 0)}
      {FINDER(14, 0)}
      {FINDER(0, 14)}
    </svg>
  );
}

function DepositPanel() {
  const [copied, setCopied] = React.useState(false);
  const address = 'TKzxd8RcM4N5xT8wpDqLnVj4nAhM7eq2yX';
  const copy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 1400);
  };
  return (
    <div style={depositPanelStyles.wrap}>
      <div style={depositPanelStyles.head}>
        <div style={depositPanelStyles.title}>Пополнить · USDT</div>
        <div style={depositPanelStyles.sub}>Сеть TRC-20</div>
      </div>
      <div style={depositPanelStyles.qrRow}>
        <div style={depositPanelStyles.qr}><FakeQR/></div>
        <div style={depositPanelStyles.addressBox}>
          <div style={depositPanelStyles.addressLbl}>Ваш адрес для пополнения</div>
          <div style={depositPanelStyles.addressField}>
            <div style={depositPanelStyles.addressVal}>{address}</div>
            <button style={depositPanelStyles.copyBtn} onClick={copy}>
              {copied ? <><IcCheck size={12} stroke="var(--success)"/> Готово</> : <><IcCopy size={12}/> Копировать</>}
            </button>
          </div>
          <div style={depositPanelStyles.notice}>
            <IcInfo size={14}/>
            <span>Переводите только USDT в сети TRC-20. Депозит зачисляется после подтверждения администратором.</span>
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { DepositPanel });

// resources/js/components/cascade/wallet/DepositPanel.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

interface QrCell {
    x: number;
    y: number;
}

const props = withDefaults(defineProps<{ address?: string | null }>(), {
    address: null,
});

const hasAddress = computed<boolean>(() => !!props.address);
const displayAddress = computed<string>(
    () => props.address ?? 'Адрес генерируется…',
);

const copied = ref(false);

function copy(): void {
    if (!props.address) {
        return;
    }
    navigator.clipboard.writeText(props.address);
    copied.value = true;
    setTimeout(() => {
        copied.value = false;
    }, 1400);
}

// Deterministic pseudo QR pattern — mirrors the React FakeQR component.
const qrCells = computed<QrCell[]>(() => {
    const cells = 21;
    const result: QrCell[] = [];

    for (let r = 0; r < cells; r++) {
        for (let c = 0; c < cells; c++) {
            const inFinder =
                (r < 7 && c < 7) ||
                (r < 7 && c >= cells - 7) ||
                (r >= cells - 7 && c < 7);
            const on = (r * 7 + c * 13 + r * c) % 5 < 2;

            if (on && !inFinder) {
                result.push({ x: c, y: r });
            }
        }
    }

    return result;
});

const finders: { x: number; y: number }[] = [
    { x: 0, y: 0 },
    { x: 14, y: 0 },
    { x: 0, y: 14 },
];
</script>

<template>
    <div
        class="flex flex-col gap-3.5 rounded-[20px] bg-white px-6 pt-6 pb-[22px]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-baseline gap-2.5">
            <div
                class="text-[18px] font-semibold tracking-[-0.01em]"
                style="color: var(--c-fg1); font-family: var(--c-font-display)"
            >
                Пополнить · USDT
            </div>
            <div class="text-xs" style="color: var(--c-fg3)">Сеть TRC-20</div>
        </div>

        <div class="flex items-center gap-[18px]">
            <div
                class="h-[124px] w-[124px] shrink-0 rounded-2xl bg-white p-2"
                style="box-shadow: inset 0 0 0 1px var(--c-hairline)"
            >
                <svg
                    viewBox="0 0 21 21"
                    width="100%"
                    height="100%"
                    shape-rendering="crispEdges"
                >
                    <rect
                        v-for="(cell, i) in qrCells"
                        :key="i"
                        :x="cell.x"
                        :y="cell.y"
                        width="1"
                        height="1"
                        fill="#1D1D1F"
                    />
                    <g v-for="f in finders" :key="`f${f.x},${f.y}`">
                        <rect
                            :x="f.x"
                            :y="f.y"
                            width="7"
                            height="7"
                            fill="#1D1D1F"
                        />
                        <rect
                            :x="f.x + 1"
                            :y="f.y + 1"
                            width="5"
                            height="5"
                            fill="#fff"
                        />
                        <rect
                            :x="f.x + 2"
                            :y="f.y + 2"
                            width="3"
                            height="3"
                            fill="#1D1D1F"
                        />
                    </g>
                </svg>
            </div>

            <div class="flex flex-1 flex-col gap-2.5">
                <div class="text-xs font-semibold" style="color: var(--c-fg2)">
                    Ваш адрес для пополнения
                </div>
                <div
                    class="flex items-center gap-2 rounded-[10px] py-2 pr-2 pl-3.5"
                    style="background: var(--c-bg-elevated)"
                >
                    <div
                        class="flex-1 overflow-hidden text-[13px] text-ellipsis whitespace-nowrap"
                        :style="{
                            color: hasAddress ? 'var(--c-fg1)' : 'var(--c-fg3)',
                            fontFamily: 'var(--c-font-mono)',
                        }"
                    >
                        {{ displayAddress }}
                    </div>
                    <button
                        :disabled="!hasAddress"
                        class="inline-flex h-[30px] items-center gap-1.5 rounded-lg bg-white px-3 text-xs font-semibold"
                        :class="
                            hasAddress ? '' : 'cursor-not-allowed opacity-50'
                        "
                        style="
                            color: var(--c-fg1);
                            box-shadow:
                                0 1px 2px rgba(0, 0, 0, 0.06),
                                0 0 0 0.5px rgba(0, 0, 0, 0.04);
                        "
                        @click="copy"
                    >
                        <template v-if="copied">
                            <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="var(--c-success)"
                                stroke-width="1.5"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                            >
                                <path d="M5 12l5 5 9-11" />
                            </svg>
                            Готово
                        </template>
                        <template v-else>
                            <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="1.5"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                            >
                                <rect
                                    x="9"
                                    y="9"
                                    width="11"
                                    height="11"
                                    rx="2"
                                />
                                <rect
                                    x="4"
                                    y="4"
                                    width="11"
                                    height="11"
                                    rx="2"
                                />
                            </svg>
                            Копировать
                        </template>
                    </button>
                </div>
                <div
                    class="flex gap-2.5 rounded-[10px] px-3 py-2.5 text-xs leading-[1.45]"
                    style="
                        background: var(--c-accent-bg);
                        color: var(--c-accent-press);
                    "
                >
                    <svg
                        class="shrink-0"
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <circle cx="12" cy="12" r="9" />
                        <path d="M12 8v.01M12 11v5" />
                    </svg>
                    <span
                        >Переводите только USDT в сети TRC-20. Депозит
                        зачисляется после подтверждения администратором.</span
                    >
                </div>
            </div>
        </div>
    </div>
</template>
