// ui_kits/wallet/WithdrawPanel.jsx
const withdrawPanelStyles = {
  wrap: {
    background: '#fff', borderRadius: 20,
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    padding: '24px 24px 22px',
    display: 'flex', flexDirection: 'column', gap: 14,
  },
  head: { display: 'flex', alignItems: 'baseline', gap: 10 },
  title: { fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 600, letterSpacing: '-0.01em' },
  sub: { fontSize: 12, color: 'var(--fg3)' },

  balanceRow: {
    background: 'var(--bg-elevated)', borderRadius: 12,
    padding: '12px 14px',
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
  },
  balLbl: { fontSize: 12, color: 'var(--fg2)' },
  balVal: { fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: 14, color: 'var(--fg1)', fontVariantNumeric: 'tabular-nums' },

  field: { display: 'flex', flexDirection: 'column', gap: 6 },
  label: { fontSize: 12, fontWeight: 600, color: 'var(--fg2)' },
  input: {
    height: 44, padding: '0 14px',
    borderRadius: 11,
    background: '#fff',
    boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.10)',
    fontSize: 15, color: 'var(--fg1)', fontFamily: 'var(--font-text)',
    border: 0, outline: 'none',
  },
  inputAmt: {
    fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums',
    fontWeight: 600, fontSize: 18,
  },
  chips: { display: 'flex', gap: 6, marginTop: 6 },
  chip: {
    padding: '5px 11px', borderRadius: 999,
    background: 'var(--bg-elevated)', border: 0,
    fontSize: 12, fontWeight: 600, color: 'var(--fg1)',
    cursor: 'pointer', fontFamily: 'inherit',
  },

  notice: {
    display: 'flex', gap: 10, padding: '10px 12px',
    background: 'var(--warning-bg)', color: '#8c5400',
    fontSize: 12, lineHeight: 1.45, borderRadius: 10,
  },

  submit: (enabled) => ({
    height: 44, borderRadius: 12, border: 0,
    background: enabled ? 'var(--accent)' : 'var(--bg-elevated)',
    color: enabled ? '#fff' : 'var(--fg3)',
    fontSize: 14, fontWeight: 600, fontFamily: 'inherit',
    cursor: enabled ? 'pointer' : 'not-allowed',
    marginTop: 4,
  }),
};

function WithdrawPanel({ balance = 1248 }) {
  const [amount, setAmount] = React.useState('');
  const [address, setAddress] = React.useState('');
  const n = parseFloat(amount) || 0;
  const valid = n >= 30 && n <= balance && address.length > 4;

  return (
    <div style={withdrawPanelStyles.wrap}>
      <div style={withdrawPanelStyles.head}>
        <div style={withdrawPanelStyles.title}>Вывод средств</div>
        <div style={withdrawPanelStyles.sub}>Без комиссии · TRC-20</div>
      </div>

      <div style={withdrawPanelStyles.balanceRow}>
        <span style={withdrawPanelStyles.balLbl}>Доступно к выводу</span>
        <span style={withdrawPanelStyles.balVal}>{balance.toLocaleString('ru-RU')} USDT</span>
      </div>

      <div style={withdrawPanelStyles.field}>
        <label style={withdrawPanelStyles.label}>Сумма</label>
        <input
          style={{...withdrawPanelStyles.input, ...withdrawPanelStyles.inputAmt}}
          placeholder="0,00"
          value={amount}
          onChange={e => setAmount(e.target.value.replace(/[^0-9.,]/g, ''))}/>
        <div style={withdrawPanelStyles.chips}>
          <button style={withdrawPanelStyles.chip} onClick={() => setAmount('30')}>Мин. 30</button>
          <button style={withdrawPanelStyles.chip} onClick={() => setAmount(String(Math.floor(balance / 2)))}>50%</button>
          <button style={withdrawPanelStyles.chip} onClick={() => setAmount(String(balance))}>Всё</button>
        </div>
      </div>

      <div style={withdrawPanelStyles.field}>
        <label style={withdrawPanelStyles.label}>Адрес кошелька</label>
        <input
          style={withdrawPanelStyles.input}
          placeholder="TRC-20 адрес"
          value={address}
          onChange={e => setAddress(e.target.value)}/>
      </div>

      <div style={withdrawPanelStyles.notice}>
        <IcInfo size={14}/>
        <span>
          Заявка получит статус «В ожидании выплаты», ваши записи в очередях перейдут в серый статус.
          Холд — 72 часа. Минимальная сумма — 30 USDT.
        </span>
      </div>

      <button style={withdrawPanelStyles.submit(valid)} disabled={!valid}>
        {n > 0 && n < 30 ? 'Минимум 30 USDT' :
         n > balance ? 'Недостаточно средств' :
         'Создать заявку'}
      </button>
    </div>
  );
}

Object.assign(window, { WithdrawPanel });

// resources/js/components/cascade/wallet/WithdrawPanel.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { router } from '@inertiajs/vue3';

const props = withDefaults(
    defineProps<{
        balance?: number;
        minWithdrawal?: number;
    }>(),
    {
        balance: 0,
        minWithdrawal: 30,
    },
);

const amount = ref('');
const address = ref('');

const numericAmount = computed<number>(() => parseFloat(amount.value) || 0);

const valid = computed<boolean>(
    () =>
        numericAmount.value >= props.minWithdrawal &&
        numericAmount.value <= props.balance &&
        address.value.length > 4,
);

const submitLabel = computed<string>(() => {
    if (numericAmount.value > 0 && numericAmount.value < props.minWithdrawal) {
        return `Минимум ${props.minWithdrawal} USDT`;
    }

    if (numericAmount.value > props.balance) {
        return 'Недостаточно средств';
    }

    return 'Создать заявку';
});

const formattedBalance = computed<string>(() =>
    props.balance.toLocaleString('ru-RU'),
);

function onAmountInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    amount.value = target.value.replace(/[^0-9.,]/g, '');
}

function setMin(): void {
    amount.value = String(props.minWithdrawal);
}

function setHalf(): void {
    amount.value = String(Math.floor(props.balance / 2));
}

function setAll(): void {
    amount.value = String(props.balance);
}

function submit(): void {
    if (!valid.value) return;
    router.post(
        '/withdrawals',
        { amount: numericAmount.value, wallet_address: address.value },
        {
            preserveScroll: true,
            onSuccess: () => {
                amount.value = '';
                address.value = '';
            },
        },
    );
}
</script>

<template>
    <div
        class="flex flex-col gap-3.5 rounded-[20px] bg-white px-6 pt-6 pb-[22px]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-baseline gap-2.5">
            <div
                class="text-[18px] font-semibold tracking-[-0.01em]"
                style="color: var(--c-fg1); font-family: var(--c-font-display)"
            >
                Вывод средств
            </div>
            <div class="text-xs" style="color: var(--c-fg3)">
                Без комиссии · TRC-20
            </div>
        </div>

        <div
            class="flex items-center justify-between rounded-xl px-3.5 py-3"
            style="background: var(--c-bg-elevated)"
        >
            <span class="text-xs" style="color: var(--c-fg2)"
                >Доступно к выводу</span
            >
            <span
                class="text-sm font-semibold"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-mono);
                    font-variant-numeric: tabular-nums;
                "
                >{{ formattedBalance }} USDT</span
            >
        </div>

        <div class="flex flex-col gap-1.5">
            <label class="text-xs font-semibold" style="color: var(--c-fg2)"
                >Сумма</label
            >
            <input
                :value="amount"
                class="h-11 rounded-[11px] border-0 bg-white px-3.5 text-[18px] font-semibold outline-none"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-mono);
                    font-variant-numeric: tabular-nums;
                    box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.1);
                "
                placeholder="0,00"
                @input="onAmountInput"
            />
            <div class="mt-1.5 flex gap-1.5">
                <button
                    class="rounded-full border-0 px-[11px] py-[5px] text-xs font-semibold"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg1);
                    "
                    @click="setMin"
                >
                    Мин. {{ props.minWithdrawal }}
                </button>
                <button
                    class="rounded-full border-0 px-[11px] py-[5px] text-xs font-semibold"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg1);
                    "
                    @click="setHalf"
                >
                    50%
                </button>
                <button
                    class="rounded-full border-0 px-[11px] py-[5px] text-xs font-semibold"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg1);
                    "
                    @click="setAll"
                >
                    Всё
                </button>
            </div>
        </div>

        <div class="flex flex-col gap-1.5">
            <label class="text-xs font-semibold" style="color: var(--c-fg2)"
                >Адрес кошелька</label
            >
            <input
                v-model="address"
                class="h-11 rounded-[11px] border-0 bg-white px-3.5 text-[15px] outline-none"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-text);
                    box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.1);
                "
                placeholder="TRC-20 адрес"
            />
        </div>

        <div
            class="flex gap-2.5 rounded-[10px] px-3 py-2.5 text-xs leading-[1.45]"
            style="background: var(--c-warning-bg); color: #8c5400"
        >
            <svg
                class="shrink-0"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
            >
                <circle cx="12" cy="12" r="9" />
                <path d="M12 8v.01M12 11v5" />
            </svg>
            <span>
                Заявка получит статус «В ожидании выплаты», ваши записи в
                очередях перейдут в серый статус. Холд — 72 часа. Минимальная
                сумма — {{ props.minWithdrawal }} USDT.
            </span>
        </div>

        <button
            :disabled="!valid"
            class="mt-1 h-11 rounded-xl border-0 text-sm font-semibold"
            :class="valid ? 'cursor-pointer' : 'cursor-not-allowed'"
            :style="
                valid
                    ? 'background: var(--c-accent); color: #fff'
                    : 'background: var(--c-bg-elevated); color: var(--c-fg3)'
            "
            @click="submit"
        >
            {{ submitLabel }}
        </button>
    </div>
</template>
