// ui_kits/admin/QueueManager.jsx
const queueManagerStyles = {
  tabs: {
    display: 'inline-flex', background: 'var(--bg-elevated)', borderRadius: 11, padding: 3, gap: 3,
  },
  tab: (active, color) => ({
    border: 0, padding: '8px 16px',
    background: active ? '#fff' : 'transparent',
    boxShadow: active ? '0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)' : 'none',
    fontSize: 13, fontWeight: 600, color: 'var(--fg1)',
    borderRadius: 9, cursor: 'pointer', fontFamily: 'inherit',
    display: 'inline-flex', alignItems: 'center', gap: 8,
  }),
  tabDot: (color) => ({ width: 8, height: 8, borderRadius: '50%', background: color }),

  row: {
    display: 'flex', alignItems: 'center', gap: 14,
    padding: '14px 24px',
    borderBottom: '1px solid var(--hairline-soft)',
  },
  pos: {
    width: 32, height: 32, borderRadius: 10,
    background: 'var(--bg-elevated)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700,
    color: 'var(--fg2)', flexShrink: 0,
  },
  posFirst: {
    background: 'var(--accent-bg)', color: 'var(--accent-press)',
  },
  user: { fontSize: 14, fontWeight: 600, color: 'var(--fg1)' },
  meta: { fontSize: 12, color: 'var(--fg3)', marginTop: 2 },

  cellsRow: { display: 'flex', gap: 3 },
  cell: (filled) => ({
    width: 18, height: 22, borderRadius: 4,
    background: filled ? 'var(--success)' : 'var(--cell-empty-bg)',
    boxShadow: filled ? 'none' : 'inset 0 0 0 1px var(--cell-empty-ring)',
  }),

  timer: (status) => ({
    fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 500,
    color: status === 'ready' ? 'var(--success)' :
           status === 'locked' ? 'var(--accent)' :
           status === 'grey' ? 'var(--fg3)' : 'var(--fg2)',
    fontVariantNumeric: 'tabular-nums',
    minWidth: 110, textAlign: 'right',
  }),

  actionBtn: {
    height: 30, width: 30,
    borderRadius: 8,
    background: 'var(--bg-elevated)',
    border: 0, cursor: 'pointer', color: 'var(--fg2)',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
  },
};

const QUEUE_DATA = {
  20: [
    { pos: 1, user: 'u_4821', filled: 4, status: 'locked', timer: '2 д 14:22:08', joined: '5 д назад' },
    { pos: 2, user: 'u_9182', filled: 3, status: 'locked', timer: '4 д 06:00:00', joined: '3 д назад' },
    { pos: 3, user: 'u_3019', filled: 2, status: 'locked', timer: '5 д 12:14:00', joined: '2 д назад' },
    { pos: 4, user: 'u_7702', filled: 1, status: 'locked', timer: '6 д 21:08:00', joined: 'вчера' },
    { pos: 5, user: 'u_8893', filled: 0, status: 'locked', timer: '6 д 23:48:11', joined: '12 мин назад' },
  ],
  100: [
    { pos: 1, user: 'u_5512', filled: 5, status: 'ready',  timer: 'Готов',           joined: '8 д назад' },
    { pos: 2, user: 'u_2210', filled: 4, status: 'locked', timer: '1 д 02:18:00',     joined: '6 д назад' },
    { pos: 3, user: 'u_1010', filled: 2, status: 'locked', timer: '3 д 15:08:00',     joined: '4 д назад' },
    { pos: 4, user: 'u_3144', filled: 0, status: 'grey',   timer: 'Серый статус',     joined: '—' },
  ],
  700: [
    { pos: 1, user: 'u_2007', filled: 3, status: 'locked', timer: '3 д 09:11:00',     joined: '4 д назад' },
    { pos: 2, user: 'u_1101', filled: 1, status: 'locked', timer: '6 д 03:14:55',     joined: 'вчера' },
  ],
  2000: [
    { pos: 1, user: 'u_7702', filled: 2, status: 'locked', timer: '6 д 03:14:55',     joined: '12 ч назад' },
  ],
};

const TIERS = [
  { id: 20,   color: 'var(--level-1)', label: 'Очередь 20' },
  { id: 100,  color: 'var(--level-2)', label: 'Очередь 100' },
  { id: 700,  color: 'var(--level-3)', label: 'Очередь 700' },
  { id: 2000, color: 'var(--level-4)', label: 'Очередь 2000' },
];

function QueueManager() {
  const [tier, setTier] = React.useState(20);
  const data = QUEUE_DATA[tier];

  return (
    <div style={tableStyles.panel}>
      <div style={tableStyles.head}>
        <div>
          <div style={tableStyles.title}>Очереди</div>
          <div style={tableStyles.sub}>Каждый уровень — изолированный «котёл». Ликвидность не пересекается между тарифами.</div>
        </div>
      </div>
      <div style={{ padding: '0 24px 14px', borderBottom: '1px solid var(--hairline)' }}>
        <div style={queueManagerStyles.tabs}>
          {TIERS.map(t => (
            <button key={t.id} style={queueManagerStyles.tab(tier === t.id, t.color)} onClick={() => setTier(t.id)}>
              <span style={queueManagerStyles.tabDot(t.color)}/>
              {t.label}
              <span style={{ marginLeft: 4, fontSize: 11, color: 'var(--fg3)', fontVariantNumeric: 'tabular-nums' }}>
                {QUEUE_DATA[t.id].length}
              </span>
            </button>
          ))}
        </div>
      </div>

      {data.map(r => (
        <div key={r.user} style={queueManagerStyles.row}>
          <div style={{...queueManagerStyles.pos, ...(r.pos === 1 ? queueManagerStyles.posFirst : {})}}>
            {r.pos}
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={queueManagerStyles.user}>{r.user}</div>
            <div style={queueManagerStyles.meta}>В очереди с {r.joined}</div>
          </div>

          <div style={queueManagerStyles.cellsRow}>
            {Array.from({ length: 5 }).map((_, i) => (
              <div key={i} style={queueManagerStyles.cell(i < r.filled)}/>
            ))}
          </div>

          <div style={queueManagerStyles.timer(r.status)}>
            {r.status === 'ready' && '● Готов'}
            {r.status === 'locked' && r.timer}
            {r.status === 'grey' && '⊘ Серый'}
          </div>

          <div style={{ display: 'flex', gap: 6 }}>
            <button style={queueManagerStyles.actionBtn} title="В начало"><IcArrowUp size={14}/></button>
            <button style={queueManagerStyles.actionBtn} title="В конец"><IcArrowDown size={14}/></button>
            <button style={queueManagerStyles.actionBtn} title="Удалить"><IcClose size={14}/></button>
          </div>
        </div>
      ))}
    </div>
  );
}

Object.assign(window, { QueueManager });

// resources/js/components/cascade/admin/QueueManager.vue
<script setup lang="ts">
import { router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

type QueueRowStatus = 'ready' | 'locked' | 'grey';

interface QueueRow {
    raw_id: number;
    pos: number;
    user: string;
    filled: number;
    status: QueueRowStatus;
    timer: string;
    joined: string;
}

const props = defineProps<{ initialQueues: Record<string, QueueRow[]> }>();

const TIERS: { id: string; color: string; label: string }[] = [
    { id: '1', color: 'var(--c-level-1)', label: 'Очередь 20' },
    { id: '2', color: 'var(--c-level-2)', label: 'Очередь 100' },
    { id: '3', color: 'var(--c-level-3)', label: 'Очередь 700' },
    { id: '4', color: 'var(--c-level-4)', label: 'Очередь 2000' },
];

const visibleTiers = computed(() =>
    TIERS.filter((t) => t.id in props.initialQueues),
);

const tier = ref<string>(visibleTiers.value[0]?.id ?? '1');

const data = computed(() => props.initialQueues[tier.value] ?? []);

function moveToFront(row: QueueRow): void {
    router.post(
        `/admin/queue/${row.raw_id}/move-front`,
        {},
        { preserveScroll: true },
    );
}

function moveToBack(row: QueueRow): void {
    router.post(
        `/admin/queue/${row.raw_id}/move-back`,
        {},
        { preserveScroll: true },
    );
}

function remove(row: QueueRow): void {
    router.post(
        `/admin/queue/${row.raw_id}/remove`,
        {},
        { preserveScroll: true },
    );
}

function timerColor(status: QueueRowStatus): string {
    switch (status) {
        case 'ready':
            return 'var(--c-success)';
        case 'locked':
            return 'var(--c-accent)';
        case 'grey':
            return 'var(--c-fg3)';
        default:
            return 'var(--c-fg2)';
    }
}
</script>

<template>
    <div
        class="overflow-hidden rounded-[18px] bg-[var(--c-bg-card)]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-center gap-3.5 px-6 pt-5 pb-3.5">
            <div>
                <div
                    class="text-[20px] font-semibold tracking-[-0.01em]"
                    style="
                        color: var(--c-fg1);
                        font-family: var(--c-font-display);
                    "
                >
                    Очереди
                </div>
                <div class="text-[13px]" style="color: var(--c-fg3)">
                    Каждый уровень — изолированный «котёл». Ликвидность не
                    пересекается между тарифами.
                </div>
            </div>
        </div>

        <div
            class="px-6 pb-3.5"
            style="border-bottom: 1px solid var(--c-hairline)"
        >
            <div
                class="inline-flex gap-[3px] rounded-[11px] p-[3px]"
                style="background: var(--c-bg-elevated)"
            >
                <button
                    v-for="t in visibleTiers"
                    :key="t.id"
                    class="inline-flex items-center gap-2 rounded-[9px] px-4 py-2 text-[13px] font-semibold"
                    style="color: var(--c-fg1)"
                    :style="
                        tier === t.id
                            ? 'background: var(--c-bg-active); box-shadow: 0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)'
                            : 'background: transparent'
                    "
                    @click="tier = t.id"
                >
                    <span
                        class="h-2 w-2 rounded-full"
                        :style="{ background: t.color }"
                    />
                    {{ t.label }}
                    <span
                        class="ml-1 text-[11px]"
                        style="
                            color: var(--c-fg3);
                            font-variant-numeric: tabular-nums;
                        "
                    >
                        {{ (initialQueues[t.id] ?? []).length }}
                    </span>
                </button>
            </div>
        </div>

        <div
            v-for="row in data"
            :key="row.raw_id"
            class="flex items-center gap-3.5 px-6 py-3.5"
            style="border-bottom: 1px solid var(--c-hairline-soft)"
        >
            <div
                class="flex h-8 w-8 shrink-0 items-center justify-center rounded-[10px] text-xs font-bold"
                style="font-family: var(--c-font-mono)"
                :style="
                    row.pos === 1
                        ? 'background: var(--c-accent-bg); color: var(--c-accent-press)'
                        : 'background: var(--c-bg-elevated); color: var(--c-fg2)'
                "
            >
                {{ row.pos }}
            </div>

            <div class="min-w-0 flex-1">
                <div class="text-sm font-semibold" style="color: var(--c-fg1)">
                    {{ row.user }}
                </div>
                <div class="mt-0.5 text-xs" style="color: var(--c-fg3)">
                    В очереди с {{ row.joined }}
                </div>
            </div>

            <div class="flex gap-[3px]">
                <div
                    v-for="i in 5"
                    :key="i"
                    class="h-[22px] w-[18px] rounded-[4px]"
                    :style="
                        i <= row.filled
                            ? 'background: var(--c-success)'
                            : 'background: var(--c-cell-empty-bg); box-shadow: inset 0 0 0 1px var(--c-cell-empty-ring)'
                    "
                />
            </div>

            <div
                class="text-right text-xs font-medium"
                :style="{
                    color: timerColor(row.status),
                    fontFamily: 'var(--c-font-mono)',
                    fontVariantNumeric: 'tabular-nums',
                    minWidth: '110px',
                }"
            >
                <template v-if="row.status === 'ready'">● Готов</template>
                <template v-else-if="row.status === 'locked'">{{
                    row.timer
                }}</template>
                <template v-else-if="row.status === 'grey'">⊘ Серый</template>
            </div>

            <div class="flex gap-1.5">
                <button
                    class="inline-flex h-[30px] w-[30px] items-center justify-center rounded-lg"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg2);
                    "
                    title="В начало"
                    @click="moveToFront(row)"
                >
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M12 19V5M6 11l6-6 6 6" />
                    </svg>
                </button>
                <button
                    class="inline-flex h-[30px] w-[30px] items-center justify-center rounded-lg"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg2);
                    "
                    title="В конец"
                    @click="moveToBack(row)"
                >
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M12 5v14M6 13l6 6 6-6" />
                    </svg>
                </button>
                <button
                    class="inline-flex h-[30px] w-[30px] items-center justify-center rounded-lg"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg2);
                    "
                    title="Удалить"
                    @click="remove(row)"
                >
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M6 6l12 12M18 6l-12 12" />
                    </svg>
                </button>
            </div>
        </div>

        <div
            v-if="data.length === 0"
            class="px-6 py-10 text-center text-sm"
            style="color: var(--c-fg3)"
        >
            Очередь пуста
        </div>
    </div>
</template>
