// ui_kits/admin/Settings.jsx
const settingsStyles = {
  panel: {
    background: '#fff', borderRadius: 18,
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    padding: '24px 28px',
  },
  group: { marginBottom: 28 },
  groupLabel: {
    fontSize: 11, fontWeight: 700, letterSpacing: '0.06em',
    color: 'var(--fg3)', textTransform: 'uppercase',
    marginBottom: 12,
  },
  row: {
    display: 'flex', alignItems: 'center', gap: 16,
    padding: '14px 0',
    borderTop: '1px solid var(--hairline-soft)',
  },
  rowFirst: { borderTop: 0 },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 14, fontWeight: 600, color: 'var(--fg1)' },
  rowSub: { fontSize: 12, color: 'var(--fg3)', marginTop: 2, lineHeight: 1.45 },

  numField: {
    width: 96,
    height: 36, padding: '0 12px',
    borderRadius: 9,
    background: '#fff',
    boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.10)',
    fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 600,
    color: 'var(--fg1)', border: 0, outline: 'none',
    textAlign: 'right',
  },
  unit: { fontSize: 12, color: 'var(--fg3)', marginLeft: 6, minWidth: 40 },

  toggle: (on) => ({
    width: 51, height: 31,
    background: on ? 'var(--success)' : 'var(--neutral-bg)',
    borderRadius: 999, position: 'relative', cursor: 'pointer',
    transition: 'background 200ms ease',
  }),
  knob: (on) => ({
    position: 'absolute', top: 2, left: 2,
    width: 27, height: 27, borderRadius: '50%', background: '#fff',
    boxShadow: '0 3px 8px rgba(0,0,0,0.15), 0 1px 1px rgba(0,0,0,0.06)',
    transform: on ? 'translateX(20px)' : 'translateX(0)',
    transition: 'transform 200ms ease',
  }),

  footer: {
    marginTop: 28, paddingTop: 20,
    borderTop: '1px solid var(--hairline)',
    display: 'flex', gap: 10, justifyContent: 'flex-end',
  },
  btn: (variant) => ({
    height: 40, padding: '0 20px', borderRadius: 11,
    border: 0, cursor: 'pointer',
    fontSize: 14, fontWeight: 600, fontFamily: 'inherit',
    background: variant === 'primary' ? 'var(--accent)' : 'var(--bg-elevated)',
    color: variant === 'primary' ? '#fff' : 'var(--fg1)',
  }),
};

function NumberRow({ title, sub, value, unit, onChange }) {
  return (
    <div style={settingsStyles.row}>
      <div style={settingsStyles.rowBody}>
        <div style={settingsStyles.rowTitle}>{title}</div>
        <div style={settingsStyles.rowSub}>{sub}</div>
      </div>
      <input style={settingsStyles.numField} value={value} onChange={e => onChange(e.target.value)}/>
      <span style={settingsStyles.unit}>{unit}</span>
    </div>
  );
}

function ToggleRow({ title, sub, on, onChange }) {
  return (
    <div style={settingsStyles.row}>
      <div style={settingsStyles.rowBody}>
        <div style={settingsStyles.rowTitle}>{title}</div>
        <div style={settingsStyles.rowSub}>{sub}</div>
      </div>
      <div style={settingsStyles.toggle(on)} onClick={onChange}>
        <div style={settingsStyles.knob(on)}/>
      </div>
    </div>
  );
}

function Settings() {
  const [absent, setAbsent] = React.useState('3');
  const [hold, setHold]     = React.useState('72');
  const [lockDays, setLockDays] = React.useState('7');
  const [minWithdraw, setMinWithdraw] = React.useState('30');
  const [autoReinvest, setAutoReinvest] = React.useState(true);
  const [ipCheck, setIpCheck] = React.useState(true);
  const [circCheck, setCircCheck] = React.useState(true);

  return (
    <div style={settingsStyles.panel}>
      <div style={settingsStyles.group}>
        <div style={settingsStyles.groupLabel}>Тайминги</div>
        <NumberRow
          title="Холд на вывод"
          sub="Заявка остаётся в статусе «В ожидании» этот срок до начала выплаты."
          value={hold} onChange={setHold} unit="часов"/>
        <NumberRow
          title="Двойной замок"
          sub="Минимальное количество дней с момента покупки уровня до возможности вывода (даже при 5/5)."
          value={lockDays} onChange={setLockDays} unit="дней"/>
        <NumberRow
          title="Авто-реинвест за прогулы"
          sub="Если пользователь не зашёл после выполнения «Двойного замка» — система запускает реинвест за него."
          value={absent} onChange={setAbsent} unit="дней"/>
      </div>

      <div style={settingsStyles.group}>
        <div style={settingsStyles.groupLabel}>Финансовые лимиты</div>
        <NumberRow
          title="Минимальная сумма вывода"
          sub="Кнопка «Вывод» в кабинете заблокирована, если итоговый баланс ниже этого порога."
          value={minWithdraw} onChange={setMinWithdraw} unit="USDT"/>
        <ToggleRow
          title="Авто-реинвест включён"
          sub="Принудительный реинвест за прогулы. Защищает кассу от «мёртвых» балансов."
          on={autoReinvest} onChange={() => setAutoReinvest(v => !v)}/>
      </div>

      <div style={settingsStyles.group}>
        <div style={settingsStyles.groupLabel}>Безопасность · анти-абуз</div>
        <ToggleRow
          title="Проверка IP / Fingerprint"
          sub="Блокировать регистрацию по реферальной ссылке при совпадении отпечатка браузера."
          on={ipCheck} onChange={() => setIpCheck(v => !v)}/>
        <ToggleRow
          title="Проверка циклических связей"
          sub="Не допускать ситуаций, где A пригласил B, а B — A. База отвергает такие записи."
          on={circCheck} onChange={() => setCircCheck(v => !v)}/>
      </div>

      <div style={settingsStyles.footer}>
        <button style={settingsStyles.btn('secondary')}>Сбросить</button>
        <button style={settingsStyles.btn('primary')}>Сохранить</button>
      </div>
    </div>
  );
}

Object.assign(window, { Settings });

// resources/js/components/cascade/admin/Settings.vue
<script setup lang="ts">
import { router } from '@inertiajs/vue3';
import { reactive } from 'vue';

interface AdminSettings {
    hold_hours: string;
    double_lock_days: string;
    auto_reinvest_days: string;
    min_withdrawal: string;
    westwallet_base_url: string;
    westwallet_public_key: string;
    westwallet_private_key: string;
    westwallet_currency: string;
    westwallet_ipn_secret: string;
    westwallet_auto_payout: boolean;
}

interface ToggleSetting {
    title: string;
    sub: string;
    on: boolean;
}

const props = defineProps<{ initialSettings: AdminSettings }>();

interface TimingSetting {
    key: keyof AdminSettings;
    title: string;
    sub: string;
    value: string;
    unit: string;
}

const timings = reactive<TimingSetting[]>([
    {
        key: 'hold_hours',
        title: 'Холд на вывод',
        sub: 'Заявка остаётся в статусе «В ожидании» этот срок до начала выплаты.',
        value: props.initialSettings.hold_hours,
        unit: 'часов',
    },
    {
        key: 'double_lock_days',
        title: 'Двойной замок',
        sub: 'Минимальное количество дней с момента покупки уровня до возможности вывода (даже при 5/5).',
        value: props.initialSettings.double_lock_days,
        unit: 'дней',
    },
    {
        key: 'auto_reinvest_days',
        title: 'Авто-реинвест за прогулы',
        sub: 'Если пользователь не зашёл после выполнения «Двойного замка» — система запускает реинвест за него.',
        value: props.initialSettings.auto_reinvest_days,
        unit: 'дней',
    },
]);

const minWithdraw = reactive({ value: props.initialSettings.min_withdrawal });

const westwallet = reactive({
    base_url: props.initialSettings.westwallet_base_url ?? '',
    public_key: props.initialSettings.westwallet_public_key ?? '',
    private_key: props.initialSettings.westwallet_private_key ?? '',
    currency: props.initialSettings.westwallet_currency ?? '',
    ipn_secret: props.initialSettings.westwallet_ipn_secret ?? '',
    auto_payout: props.initialSettings.westwallet_auto_payout ?? false,
});

interface WalletField {
    key: 'base_url' | 'public_key' | 'private_key' | 'currency' | 'ipn_secret';
    title: string;
    sub: string;
    secret: boolean;
    placeholder: string;
}

const walletFields: WalletField[] = [
    {
        key: 'base_url',
        title: 'API URL',
        sub: 'Базовый адрес WestWallet API.',
        secret: false,
        placeholder: 'https://api.westwallet.io',
    },
    {
        key: 'public_key',
        title: 'Public Key',
        sub: 'Публичный ключ API (X-API-KEY).',
        secret: false,
        placeholder: '—',
    },
    {
        key: 'private_key',
        title: 'Private Key',
        sub: 'Приватный ключ для подписи запросов. Хранится в БД.',
        secret: true,
        placeholder: '—',
    },
    {
        key: 'currency',
        title: 'Валюта',
        sub: 'Код валюты для генерации адресов (USDT TRC-20 → USDTTRC).',
        secret: false,
        placeholder: 'USDTTRC',
    },
    {
        key: 'ipn_secret',
        title: 'IPN Secret',
        sub: 'Секрет для проверки подписи входящих IPN-уведомлений.',
        secret: true,
        placeholder: '—',
    },
];

const financialToggles = reactive<ToggleSetting[]>([
    {
        title: 'Авто-реинвест включён',
        sub: 'Принудительный реинвест за прогулы. Защищает кассу от «мёртвых» балансов.',
        on: true,
    },
]);

const securityToggles = reactive<ToggleSetting[]>([
    {
        title: 'Проверка IP / Fingerprint',
        sub: 'Блокировать регистрацию по реферальной ссылке при совпадении отпечатка браузера.',
        on: true,
    },
    {
        title: 'Проверка циклических связей',
        sub: 'Не допускать ситуаций, где A пригласил B, а B — A. База отвергает такие записи.',
        on: true,
    },
]);

function toggle(setting: ToggleSetting): void {
    setting.on = !setting.on;
}

function save(): void {
    router.post(
        '/admin/settings',
        {
            hold_hours: timings[0].value,
            double_lock_days: timings[1].value,
            auto_reinvest_days: timings[2].value,
            min_withdrawal: minWithdraw.value,
            westwallet_base_url: westwallet.base_url,
            westwallet_public_key: westwallet.public_key,
            westwallet_private_key: westwallet.private_key,
            westwallet_currency: westwallet.currency,
            westwallet_ipn_secret: westwallet.ipn_secret,
            westwallet_auto_payout: westwallet.auto_payout,
        },
        { preserveScroll: true },
    );
}

function reset(): void {
    timings[0].value = props.initialSettings.hold_hours;
    timings[1].value = props.initialSettings.double_lock_days;
    timings[2].value = props.initialSettings.auto_reinvest_days;
    minWithdraw.value = props.initialSettings.min_withdrawal;
    westwallet.base_url = props.initialSettings.westwallet_base_url ?? '';
    westwallet.public_key = props.initialSettings.westwallet_public_key ?? '';
    westwallet.private_key = props.initialSettings.westwallet_private_key ?? '';
    westwallet.currency = props.initialSettings.westwallet_currency ?? '';
    westwallet.ipn_secret = props.initialSettings.westwallet_ipn_secret ?? '';
    westwallet.auto_payout =
        props.initialSettings.westwallet_auto_payout ?? false;
}
</script>

<template>
    <div
        class="rounded-[18px] bg-[var(--c-bg-card)] px-7 py-6"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="mb-7">
            <div
                class="mb-3 text-[11px] font-bold tracking-[0.06em] uppercase"
                style="color: var(--c-fg3)"
            >
                Тайминги
            </div>
            <div
                v-for="(row, i) in timings"
                :key="row.key"
                class="flex items-center gap-4 py-3.5"
                :style="
                    i === 0
                        ? ''
                        : 'border-top: 1px solid var(--c-hairline-soft)'
                "
            >
                <div class="flex-1">
                    <div
                        class="text-sm font-semibold"
                        style="color: var(--c-fg1)"
                    >
                        {{ row.title }}
                    </div>
                    <div
                        class="mt-0.5 text-xs leading-[1.45]"
                        style="color: var(--c-fg3)"
                    >
                        {{ row.sub }}
                    </div>
                </div>
                <input
                    v-model="row.value"
                    class="h-9 w-24 rounded-[9px] bg-[var(--c-bg-card)] px-3 text-right text-sm font-semibold outline-none"
                    style="
                        box-shadow: inset 0 0 0 1px var(--c-input-border);
                        font-family: var(--c-font-mono);
                        color: var(--c-fg1);
                    "
                />
                <span
                    class="ml-1.5 text-xs"
                    style="color: var(--c-fg3); min-width: 40px"
                >
                    {{ row.unit }}
                </span>
            </div>
        </div>

        <div class="mb-7">
            <div
                class="mb-3 text-[11px] font-bold tracking-[0.06em] uppercase"
                style="color: var(--c-fg3)"
            >
                Финансовые лимиты
            </div>
            <div class="flex items-center gap-4 py-3.5">
                <div class="flex-1">
                    <div
                        class="text-sm font-semibold"
                        style="color: var(--c-fg1)"
                    >
                        Минимальная сумма вывода
                    </div>
                    <div
                        class="mt-0.5 text-xs leading-[1.45]"
                        style="color: var(--c-fg3)"
                    >
                        Кнопка «Вывод» в кабинете заблокирована, если итоговый
                        баланс ниже этого порога.
                    </div>
                </div>
                <input
                    v-model="minWithdraw.value"
                    class="h-9 w-24 rounded-[9px] bg-[var(--c-bg-card)] px-3 text-right text-sm font-semibold outline-none"
                    style="
                        box-shadow: inset 0 0 0 1px var(--c-input-border);
                        font-family: var(--c-font-mono);
                        color: var(--c-fg1);
                    "
                />
                <span
                    class="ml-1.5 text-xs"
                    style="color: var(--c-fg3); min-width: 40px"
                >
                    USDT
                </span>
            </div>
            <div
                v-for="row in financialToggles"
                :key="row.title"
                class="flex items-center gap-4 py-3.5"
                style="border-top: 1px solid var(--c-hairline-soft)"
            >
                <div class="flex-1">
                    <div
                        class="text-sm font-semibold"
                        style="color: var(--c-fg1)"
                    >
                        {{ row.title }}
                    </div>
                    <div
                        class="mt-0.5 text-xs leading-[1.45]"
                        style="color: var(--c-fg3)"
                    >
                        {{ row.sub }}
                    </div>
                </div>
                <div
                    class="relative cursor-pointer rounded-full transition-colors duration-200 ease-in-out"
                    style="width: 51px; height: 31px"
                    :style="{
                        background: row.on
                            ? 'var(--c-success)'
                            : 'var(--c-neutral-bg)',
                    }"
                    @click="toggle(row)"
                >
                    <div
                        class="absolute rounded-full bg-[var(--c-knob)] transition-transform duration-200 ease-in-out"
                        style="
                            top: 2px;
                            left: 2px;
                            width: 27px;
                            height: 27px;
                            box-shadow:
                                0 3px 8px rgba(0, 0, 0, 0.15),
                                0 1px 1px rgba(0, 0, 0, 0.06);
                        "
                        :style="{
                            transform: row.on
                                ? 'translateX(20px)'
                                : 'translateX(0)',
                        }"
                    />
                </div>
            </div>
        </div>

        <div class="mb-7">
            <div
                class="mb-3 text-[11px] font-bold tracking-[0.06em] uppercase"
                style="color: var(--c-fg3)"
            >
                Безопасность · анти-абуз
            </div>
            <div
                v-for="(row, i) in securityToggles"
                :key="row.title"
                class="flex items-center gap-4 py-3.5"
                :style="
                    i === 0
                        ? ''
                        : 'border-top: 1px solid var(--c-hairline-soft)'
                "
            >
                <div class="flex-1">
                    <div
                        class="text-sm font-semibold"
                        style="color: var(--c-fg1)"
                    >
                        {{ row.title }}
                    </div>
                    <div
                        class="mt-0.5 text-xs leading-[1.45]"
                        style="color: var(--c-fg3)"
                    >
                        {{ row.sub }}
                    </div>
                </div>
                <div
                    class="relative cursor-pointer rounded-full transition-colors duration-200 ease-in-out"
                    style="width: 51px; height: 31px"
                    :style="{
                        background: row.on
                            ? 'var(--c-success)'
                            : 'var(--c-neutral-bg)',
                    }"
                    @click="toggle(row)"
                >
                    <div
                        class="absolute rounded-full bg-[var(--c-knob)] transition-transform duration-200 ease-in-out"
                        style="
                            top: 2px;
                            left: 2px;
                            width: 27px;
                            height: 27px;
                            box-shadow:
                                0 3px 8px rgba(0, 0, 0, 0.15),
                                0 1px 1px rgba(0, 0, 0, 0.06);
                        "
                        :style="{
                            transform: row.on
                                ? 'translateX(20px)'
                                : 'translateX(0)',
                        }"
                    />
                </div>
            </div>
        </div>

        <div class="mb-7">
            <div
                class="mb-3 text-[11px] font-bold tracking-[0.06em] uppercase"
                style="color: var(--c-fg3)"
            >
                Платёжный шлюз · WestWallet
            </div>

            <div
                v-for="(field, i) in walletFields"
                :key="field.key"
                class="flex items-center gap-4 py-3.5"
                :style="
                    i === 0
                        ? ''
                        : 'border-top: 1px solid var(--c-hairline-soft)'
                "
            >
                <div class="flex-1">
                    <div
                        class="text-sm font-semibold"
                        style="color: var(--c-fg1)"
                    >
                        {{ field.title }}
                    </div>
                    <div
                        class="mt-0.5 text-xs leading-[1.45]"
                        style="color: var(--c-fg3)"
                    >
                        {{ field.sub }}
                    </div>
                </div>
                <input
                    v-model="westwallet[field.key]"
                    :type="field.secret ? 'password' : 'text'"
                    :placeholder="field.placeholder"
                    autocomplete="off"
                    class="h-9 w-64 rounded-[9px] bg-[var(--c-bg-card)] px-3 text-sm outline-none"
                    style="
                        box-shadow: inset 0 0 0 1px var(--c-input-border);
                        font-family: var(--c-font-mono);
                        color: var(--c-fg1);
                    "
                />
            </div>

            <div
                class="flex items-center gap-4 py-3.5"
                style="border-top: 1px solid var(--c-hairline-soft)"
            >
                <div class="flex-1">
                    <div
                        class="text-sm font-semibold"
                        style="color: var(--c-fg1)"
                    >
                        Авто-выплата при подтверждении
                    </div>
                    <div
                        class="mt-0.5 text-xs leading-[1.45]"
                        style="color: var(--c-fg3)"
                    >
                        Отправлять USDT на кошелёк автоматически при одобрении
                        заявки. Если выключено — администратор выплачивает
                        вручную.
                    </div>
                </div>
                <div
                    class="relative cursor-pointer rounded-full transition-colors duration-200 ease-in-out"
                    style="width: 51px; height: 31px"
                    :style="{
                        background: westwallet.auto_payout
                            ? 'var(--c-success)'
                            : 'var(--c-neutral-bg)',
                    }"
                    @click="westwallet.auto_payout = !westwallet.auto_payout"
                >
                    <div
                        class="absolute rounded-full bg-[var(--c-knob)] transition-transform duration-200 ease-in-out"
                        style="
                            top: 2px;
                            left: 2px;
                            width: 27px;
                            height: 27px;
                            box-shadow:
                                0 3px 8px rgba(0, 0, 0, 0.15),
                                0 1px 1px rgba(0, 0, 0, 0.06);
                        "
                        :style="{
                            transform: westwallet.auto_payout
                                ? 'translateX(20px)'
                                : 'translateX(0)',
                        }"
                    />
                </div>
            </div>
        </div>

        <div
            class="mt-7 flex justify-end gap-2.5 pt-5"
            style="border-top: 1px solid var(--c-hairline)"
        >
            <button
                class="h-10 rounded-[11px] px-5 text-sm font-semibold"
                style="background: var(--c-bg-elevated); color: var(--c-fg1)"
                @click="reset"
            >
                Сбросить
            </button>
            <button
                class="h-10 rounded-[11px] px-5 text-sm font-semibold text-white"
                style="background: var(--c-accent)"
                @click="save"
            >
                Сохранить
            </button>
        </div>
    </div>
</template>
