// ui_kits/admin/WithdrawalsTable.jsx
const WITHDRAWALS = [
  { id: '#WD-1281', user: 'u_4821', amount: 1050.00, holdLeft: 6,   total: 72, status: 'hold',     created: 'сегодня 09:14' },
  { id: '#WD-1280', user: 'u_3019', amount: 30.00,   holdLeft: 18,  total: 72, status: 'hold',     created: 'сегодня 02:30' },
  { id: '#WD-1279', user: 'u_5512', amount: 150.00,  holdLeft: 0,   total: 72, status: 'pending',  created: 'вчера 11:22' },
  { id: '#WD-1278', user: 'u_7702', amount: 3000.00, holdLeft: 0,   total: 72, status: 'pending',  created: 'вчера 08:45' },
  { id: '#WD-1277', user: 'u_2210', amount: 30.00,   holdLeft: null, total: 72, status: 'approved', created: '2 дн назад' },
  { id: '#WD-1276', user: 'u_8893', amount: 150.00,  holdLeft: null, total: 72, status: 'rejected', created: '3 дн назад' },
];

function HoldBar({ left, total }) {
  if (left === null) return <span style={{ color: 'var(--fg3)', fontSize: 12 }}>—</span>;
  const progress = (total - left) / total;
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 120 }}>
      <div style={{ flex: 1, height: 6, background: 'var(--cell-empty-bg)', borderRadius: 3, overflow: 'hidden' }}>
        <div style={{
          width: `${Math.round(progress * 100)}%`,
          height: '100%',
          background: left === 0 ? 'var(--success)' : 'var(--accent)',
          transition: 'width 200ms ease',
        }}/>
      </div>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--fg2)', fontVariantNumeric: 'tabular-nums', minWidth: 36, textAlign: 'right' }}>
        {left}ч
      </span>
    </div>
  );
}

function WithdrawalsTable() {
  const [filter, setFilter] = React.useState('active');
  const [rows, setRows] = React.useState(WITHDRAWALS);

  const filtered = rows.filter(r => {
    if (filter === 'active') return r.status === 'hold' || r.status === 'pending';
    return r.status === filter;
  });

  const approve = id => setRows(rs => rs.map(r => r.id === id ? { ...r, status: 'approved', holdLeft: null } : r));
  const reject  = id => setRows(rs => rs.map(r => r.id === id ? { ...r, status: 'rejected', holdLeft: null } : r));

  return (
    <div style={tableStyles.panel}>
      <div style={tableStyles.head}>
        <div>
          <div style={tableStyles.title}>Заявки на вывод</div>
          <div style={tableStyles.sub}>Кнопка «Выплатить» активна только по истечении 72-часового холда</div>
        </div>
      </div>
      <div style={tableStyles.filterBar}>
        <div style={tableStyles.seg}>
          <button style={tableStyles.segBtn(filter==='active')}   onClick={() => setFilter('active')}>Активные</button>
          <button style={tableStyles.segBtn(filter==='approved')} onClick={() => setFilter('approved')}>Выплачены</button>
          <button style={tableStyles.segBtn(filter==='rejected')} onClick={() => setFilter('rejected')}>Отклонены</button>
        </div>
      </div>
      <table style={tableStyles.table}>
        <thead>
          <tr>
            <th style={tableStyles.th}>ID</th>
            <th style={tableStyles.th}>Пользователь</th>
            <th style={tableStyles.th}>Сумма</th>
            <th style={tableStyles.th}>Холд</th>
            <th style={tableStyles.th}>Создана</th>
            <th style={tableStyles.th}>Статус</th>
            <th style={{...tableStyles.th, textAlign: 'right'}}>Действие</th>
          </tr>
        </thead>
        <tbody>
          {filtered.map(r => {
            const canPay = r.status === 'pending';
            return (
              <tr key={r.id}>
                <td style={{...tableStyles.td, ...tableStyles.mono, color: 'var(--fg2)'}}>{r.id}</td>
                <td style={tableStyles.td}>{r.user}</td>
                <td style={{...tableStyles.td, ...tableStyles.mono, fontWeight: 600}}>{r.amount.toLocaleString('ru-RU', {minimumFractionDigits: 2}).replace(/,/g,' ').replace(/\s(\d{2})$/, ',$1')} USDT</td>
                <td style={tableStyles.td}><HoldBar left={r.holdLeft} total={r.total}/></td>
                <td style={{...tableStyles.td, color: 'var(--fg3)'}}>{r.created}</td>
                <td style={tableStyles.td}>
                  <span style={tableStyles.pill(r.status === 'hold' ? 'hold' : r.status)}>
                    <span style={tableStyles.pillDot(r.status === 'hold' ? 'hold' : r.status)}/>
                    {r.status === 'hold' && 'Холд'}
                    {r.status === 'pending' && 'Готова к выплате'}
                    {r.status === 'approved' && 'Выплачена'}
                    {r.status === 'rejected' && 'Отклонена'}
                  </span>
                </td>
                <td style={tableStyles.td}>
                  <div style={tableStyles.btnRow}>
                    {(r.status === 'hold' || r.status === 'pending') && (
                      <>
                        <button
                          style={{...tableStyles.btn('approve'), opacity: canPay ? 1 : 0.4, cursor: canPay ? 'pointer' : 'not-allowed'}}
                          disabled={!canPay}
                          onClick={() => canPay && approve(r.id)}>
                          <IcCheck size={12}/> Выплатить
                        </button>
                        <button style={tableStyles.btn('reject')} onClick={() => reject(r.id)}>
                          <IcClose size={12}/>
                        </button>
                      </>
                    )}
                    {(r.status === 'approved' || r.status === 'rejected') && (
                      <button style={tableStyles.btn('secondary')}>Детали</button>
                    )}
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

Object.assign(window, { WithdrawalsTable });

// resources/js/components/cascade/admin/WithdrawalsTable.vue
<script setup lang="ts">
import { router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

type WithdrawalStatus = 'hold' | 'pending' | 'approved' | 'rejected';

interface Withdrawal {
    id: string;
    raw_id: number;
    user: string;
    amount: number;
    holdLeft: number | null;
    total: number;
    status: WithdrawalStatus;
    created: string;
}

type FilterKey = 'active' | 'approved' | 'rejected';

const props = defineProps<{ initialRows: Withdrawal[] }>();

const filters: { key: FilterKey; label: string }[] = [
    { key: 'active', label: 'Активные' },
    { key: 'approved', label: 'Выплачены' },
    { key: 'rejected', label: 'Отклонены' },
];

const filter = ref<FilterKey>('active');

const filtered = computed(() => {
    return props.initialRows.filter((row) => {
        if (filter.value === 'active') {
            return row.status === 'hold' || row.status === 'pending';
        }

        return row.status === filter.value;
    });
});

function approve(row: Withdrawal): void {
    router.post(
        `/admin/withdrawals/${row.raw_id}/approve`,
        {},
        { preserveScroll: true },
    );
}

function reject(row: Withdrawal): void {
    router.post(
        `/admin/withdrawals/${row.raw_id}/reject`,
        {},
        { preserveScroll: true },
    );
}

function formatAmount(amount: number): string {
    return amount
        .toLocaleString('ru-RU', { minimumFractionDigits: 2 })
        .replace(/,/g, ' ')
        .replace(/\s(\d{2})$/, ',$1');
}

function holdProgress(row: Withdrawal): number {
    if (row.holdLeft === null) {
        return 0;
    }

    return Math.round(((row.total - row.holdLeft) / row.total) * 100);
}

const pillColors: Record<WithdrawalStatus, [string, string]> = {
    hold: ['var(--c-accent-bg)', 'var(--c-accent-press)'],
    pending: ['var(--c-warning-bg)', 'var(--c-warning-fg)'],
    approved: ['var(--c-success-bg)', 'var(--c-success-fg)'],
    rejected: ['var(--c-danger-bg)', 'var(--c-danger-fg)'],
};

const dotColors: Record<WithdrawalStatus, string> = {
    hold: 'var(--c-accent)',
    pending: 'var(--c-warning)',
    approved: 'var(--c-success)',
    rejected: 'var(--c-danger)',
};

const statusLabels: Record<WithdrawalStatus, string> = {
    hold: 'Холд',
    pending: 'Готова к выплате',
    approved: 'Выплачена',
    rejected: 'Отклонена',
};
</script>

<template>
    <div
        class="overflow-hidden rounded-[18px] bg-[var(--c-bg-card)]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-center gap-3.5 px-6 pt-5 pb-3.5">
            <div>
                <div
                    class="text-[20px] font-semibold tracking-[-0.01em]"
                    style="
                        color: var(--c-fg1);
                        font-family: var(--c-font-display);
                    "
                >
                    Заявки на вывод
                </div>
                <div class="text-[13px]" style="color: var(--c-fg3)">
                    Кнопка «Выплатить» активна только по истечении 72-часового
                    холда
                </div>
            </div>
        </div>

        <div
            class="flex items-center gap-2 px-6 pb-3.5"
            style="border-bottom: 1px solid var(--c-hairline)"
        >
            <div
                class="inline-flex gap-0.5 rounded-[9px] p-0.5"
                style="background: var(--c-bg-elevated)"
            >
                <button
                    v-for="f in filters"
                    :key="f.key"
                    class="rounded-[7px] px-3 py-1.5 text-xs font-semibold"
                    style="color: var(--c-fg1)"
                    :style="
                        filter === f.key
                            ? 'background: var(--c-bg-active); box-shadow: 0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)'
                            : 'background: transparent'
                    "
                    @click="filter = f.key"
                >
                    {{ f.label }}
                </button>
            </div>
        </div>

        <div class="overflow-x-auto">
            <table class="w-full min-w-[720px] border-collapse">
                <thead>
                    <tr>
                        <th
                            v-for="(label, i) in [
                                'ID',
                                'Пользователь',
                                'Сумма',
                                'Холд',
                                'Создана',
                                'Статус',
                            ]"
                            :key="i"
                            class="px-6 py-3 text-left text-[11px] font-semibold tracking-[0.04em] uppercase"
                            style="
                                color: var(--c-fg3);
                                border-bottom: 1px solid var(--c-hairline);
                                background: var(--c-bg);
                            "
                        >
                            {{ label }}
                        </th>
                        <th
                            class="px-6 py-3 text-right text-[11px] font-semibold tracking-[0.04em] uppercase"
                            style="
                                color: var(--c-fg3);
                                border-bottom: 1px solid var(--c-hairline);
                                background: var(--c-bg);
                            "
                        >
                            Действие
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="row in filtered" :key="row.id">
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg2);
                                font-family: var(--c-font-mono);
                                font-variant-numeric: tabular-nums;
                            "
                        >
                            {{ row.id }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            {{ row.user }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px] font-semibold"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                                font-family: var(--c-font-mono);
                                font-variant-numeric: tabular-nums;
                            "
                        >
                            {{ formatAmount(row.amount) }} USDT
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            <span
                                v-if="row.holdLeft === null"
                                class="text-xs"
                                style="color: var(--c-fg3)"
                            >
                                —
                            </span>
                            <div
                                v-else
                                class="flex items-center gap-2"
                                style="min-width: 120px"
                            >
                                <div
                                    class="h-1.5 flex-1 overflow-hidden rounded-[3px]"
                                    style="background: var(--c-cell-empty-bg)"
                                >
                                    <div
                                        class="h-full transition-[width] duration-200 ease-in-out"
                                        :style="{
                                            width: holdProgress(row) + '%',
                                            background:
                                                row.holdLeft === 0
                                                    ? 'var(--c-success)'
                                                    : 'var(--c-accent)',
                                        }"
                                    />
                                </div>
                                <span
                                    class="text-right text-[11px]"
                                    style="
                                        color: var(--c-fg2);
                                        font-family: var(--c-font-mono);
                                        font-variant-numeric: tabular-nums;
                                        min-width: 36px;
                                    "
                                >
                                    {{ row.holdLeft }}ч
                                </span>
                            </div>
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg3);
                            "
                        >
                            {{ row.created }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            <span
                                class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-[3px] text-[11px] font-semibold"
                                :style="{
                                    background: pillColors[row.status][0],
                                    color: pillColors[row.status][1],
                                }"
                            >
                                <span
                                    class="h-1.5 w-1.5 rounded-full"
                                    :style="{
                                        background: dotColors[row.status],
                                    }"
                                />
                                {{ statusLabels[row.status] }}
                            </span>
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            <div class="flex justify-end gap-1.5">
                                <template
                                    v-if="
                                        row.status === 'hold' ||
                                        row.status === 'pending'
                                    "
                                >
                                    <button
                                        class="inline-flex h-[30px] items-center gap-1.5 rounded-lg px-3 text-xs font-semibold text-white"
                                        style="background: var(--c-success)"
                                        :style="{
                                            opacity:
                                                row.status === 'pending'
                                                    ? 1
                                                    : 0.4,
                                            cursor:
                                                row.status === 'pending'
                                                    ? 'pointer'
                                                    : 'not-allowed',
                                        }"
                                        :disabled="row.status !== 'pending'"
                                        @click="
                                            row.status === 'pending' &&
                                            approve(row)
                                        "
                                    >
                                        <svg
                                            width="12"
                                            height="12"
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            stroke-width="1.5"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                        >
                                            <path d="M5 12l5 5 9-11" />
                                        </svg>
                                        Выплатить
                                    </button>
                                    <button
                                        class="inline-flex h-[30px] w-[30px] items-center justify-center rounded-lg text-white"
                                        style="background: var(--c-danger)"
                                        @click="reject(row)"
                                    >
                                        <svg
                                            width="12"
                                            height="12"
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            stroke-width="1.5"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                        >
                                            <path d="M6 6l12 12M18 6l-12 12" />
                                        </svg>
                                    </button>
                                </template>
                                <button
                                    v-else
                                    class="inline-flex h-[30px] items-center gap-1.5 rounded-lg px-3 text-xs font-semibold"
                                    style="
                                        background: var(--c-bg-elevated);
                                        color: var(--c-fg1);
                                    "
                                >
                                    Детали
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
