// resources/js/components/cascade/admin/DepositsTable.vue
<script setup lang="ts">
import { router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';


type DepositStatus = 'pending' | 'approved' | 'rejected';

interface Deposit {
    id: string;
    raw_id: number;
    user: string;
    level: number;
    amount: number;
    ref: string;
    age: string;
    status: DepositStatus;
}

type FilterKey = 'pending' | 'approved' | 'all';

const props = defineProps<{ initialRows: Deposit[] }>();

const filters: { key: FilterKey; label: string }[] = [
    { key: 'pending', label: 'Ожидают' },
    { key: 'approved', label: 'Подтверждены' },
    { key: 'all', label: 'Все' },
];

const filter = ref<FilterKey>('pending');

const filtered = computed(() => {
    if (filter.value === 'all') {
        return props.initialRows;
    }

    return props.initialRows.filter((row) => row.status === filter.value);
});

function approve(row: Deposit): void {
    router.post(`/admin/deposits/${row.raw_id}/approve`, {}, { preserveScroll: true });
}

function reject(row: Deposit): void {
    router.post(`/admin/deposits/${row.raw_id}/reject`, {}, { preserveScroll: true });
}

function formatAmount(amount: number): string {
    return amount.toLocaleString('ru-RU').replace(/,/g, ' ');
}

const pillColors: Record<DepositStatus, [string, string]> = {
    pending: ['var(--c-warning-bg)', '#8c5400'],
    approved: ['var(--c-success-bg)', '#1a6e34'],
    rejected: ['var(--c-danger-bg)', '#b32420'],
};

const dotColors: Record<DepositStatus, string> = {
    pending: 'var(--c-warning)',
    approved: 'var(--c-success)',
    rejected: 'var(--c-danger)',
};

const statusLabels: Record<DepositStatus, string> = {
    pending: 'Ожидает',
    approved: 'Подтверждён',
    rejected: 'Отклонён',
};
</script>

<template>
    <div
        class="overflow-hidden rounded-[18px] bg-white"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-center gap-3.5 px-6 pt-5 pb-3.5">
            <div>
                <div
                    class="text-[20px] font-semibold tracking-[-0.01em]"
                    style="
                        color: var(--c-fg1);
                        font-family: var(--c-font-display);
                    "
                >
                    Депозиты
                </div>
                <div class="text-[13px]" style="color: var(--c-fg3)">
                    Подтверждение запускает сплит 10 / 60 / 30 и обновляет
                    очередь
                </div>
            </div>
        </div>

        <div
            class="flex items-center gap-2 px-6 pb-3.5"
            style="border-bottom: 1px solid var(--c-hairline)"
        >
            <div
                class="inline-flex gap-0.5 rounded-[9px] p-0.5"
                style="background: var(--c-bg-elevated)"
            >
                <button
                    v-for="f in filters"
                    :key="f.key"
                    class="rounded-[7px] px-3 py-1.5 text-xs font-semibold"
                    style="color: var(--c-fg1)"
                    :style="
                        filter === f.key
                            ? 'background: #fff; box-shadow: 0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)'
                            : 'background: transparent'
                    "
                    @click="filter = f.key"
                >
                    {{ f.label }}
                </button>
            </div>
        </div>

        <div class="overflow-x-auto">
            <table class="w-full min-w-[640px] border-collapse">
                <thead>
                    <tr>
                        <th
                            v-for="(label, i) in [
                                'ID',
                                'Пользователь',
                                'Уровень',
                                'Сумма',
                                'Реферер',
                                'Время',
                                'Статус',
                            ]"
                            :key="i"
                            class="px-6 py-3 text-left text-[11px] font-semibold tracking-[0.04em] uppercase"
                            style="
                                color: var(--c-fg3);
                                border-bottom: 1px solid var(--c-hairline);
                                background: var(--c-bg);
                            "
                        >
                            {{ label }}
                        </th>
                        <th
                            class="px-6 py-3 text-right text-[11px] font-semibold tracking-[0.04em] uppercase"
                            style="
                                color: var(--c-fg3);
                                border-bottom: 1px solid var(--c-hairline);
                                background: var(--c-bg);
                            "
                        >
                            Действие
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="row in filtered" :key="row.id">
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg2);
                                font-family: var(--c-font-mono);
                                font-variant-numeric: tabular-nums;
                            "
                        >
                            {{ row.id }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            {{ row.user }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            Level {{ row.level }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px] font-semibold"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                                font-family: var(--c-font-mono);
                                font-variant-numeric: tabular-nums;
                            "
                        >
                            {{ formatAmount(row.amount) }} USDT
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg2);
                            "
                        >
                            {{ row.ref }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg3);
                            "
                        >
                            {{ row.age }}
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            <span
                                class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-[3px] text-[11px] font-semibold"
                                :style="{
                                    background: pillColors[row.status][0],
                                    color: pillColors[row.status][1],
                                }"
                            >
                                <span
                                    class="h-1.5 w-1.5 rounded-full"
                                    :style="{
                                        background: dotColors[row.status],
                                    }"
                                />
                                {{ statusLabels[row.status] }}
                            </span>
                        </td>
                        <td
                            class="px-6 py-3.5 align-middle text-[13px]"
                            style="
                                border-bottom: 1px solid var(--c-hairline-soft);
                                color: var(--c-fg1);
                            "
                        >
                            <div class="flex justify-end gap-1.5">
                                <template v-if="row.status === 'pending'">
                                    <button
                                        class="inline-flex h-[30px] items-center gap-1.5 rounded-lg px-3 text-xs font-semibold text-white"
                                        style="background: var(--c-success)"
                                        @click="approve(row)"
                                    >
                                        <svg
                                            width="12"
                                            height="12"
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            stroke-width="1.5"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                        >
                                            <path d="M5 12l5 5 9-11" />
                                        </svg>
                                        Подтвердить
                                    </button>
                                    <button
                                        class="inline-flex h-[30px] w-[30px] items-center justify-center rounded-lg text-white"
                                        style="background: var(--c-danger)"
                                        @click="reject(row)"
                                    >
                                        <svg
                                            width="12"
                                            height="12"
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            stroke-width="1.5"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                        >
                                            <path d="M6 6l12 12M18 6l-12 12" />
                                        </svg>
                                    </button>
                                </template>
                                <button
                                    v-else
                                    class="inline-flex h-[30px] items-center gap-1.5 rounded-lg px-3 text-xs font-semibold"
                                    style="
                                        background: var(--c-bg-elevated);
                                        color: var(--c-fg1);
                                    "
                                >
                                    Детали
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

// ui_kits/admin/DepositsTable.jsx
const tableStyles = {
  panel: {
    background: '#fff', borderRadius: 18,
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    overflow: 'hidden',
  },
  head: { padding: '20px 24px 14px', display: 'flex', alignItems: 'center', gap: 14 },
  title: { fontFamily: 'var(--font-display)', fontSize: 20, fontWeight: 600, letterSpacing: '-0.01em', color: 'var(--fg1)' },
  sub: { fontSize: 13, color: 'var(--fg3)' },

  filterBar: {
    padding: '0 24px 14px', display: 'flex', gap: 8, alignItems: 'center',
    borderBottom: '1px solid var(--hairline)',
  },
  seg: { display: 'inline-flex', background: 'var(--bg-elevated)', borderRadius: 9, padding: 2, gap: 2 },
  segBtn: (active) => ({
    border: 0, background: active ? '#fff' : 'transparent',
    boxShadow: active ? '0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)' : 'none',
    padding: '6px 12px', fontSize: 12, fontWeight: 600,
    color: 'var(--fg1)', borderRadius: 7, cursor: 'pointer', fontFamily: 'inherit',
  }),

  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    fontSize: 11, color: 'var(--fg3)', fontWeight: 600,
    textTransform: 'uppercase', letterSpacing: '0.04em',
    padding: '12px 24px', textAlign: 'left',
    borderBottom: '1px solid var(--hairline)',
    background: 'var(--bg)',
  },
  td: {
    padding: '14px 24px', borderBottom: '1px solid var(--hairline-soft)',
    fontSize: 13, color: 'var(--fg1)', verticalAlign: 'middle',
  },
  mono: { fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums' },
  pill: (variant) => {
    const map = {
      pending:  ['var(--warning-bg)', '#8c5400'],
      approved: ['var(--success-bg)', '#1a6e34'],
      hold:     ['var(--accent-bg)',  'var(--accent-press)'],
      grey:     ['var(--neutral-bg)', 'var(--fg2)'],
      rejected: ['var(--danger-bg)',  '#b32420'],
    };
    const [bg, fg] = map[variant] || ['var(--bg-elevated)', 'var(--fg2)'];
    return {
      display: 'inline-flex', alignItems: 'center', gap: 6,
      padding: '3px 9px', borderRadius: 999,
      fontSize: 11, fontWeight: 600,
      background: bg, color: fg,
    };
  },
  pillDot: (variant) => {
    const map = { pending: 'var(--warning)', approved: 'var(--success)', hold: 'var(--accent)', grey: 'var(--neutral)', rejected: 'var(--danger)' };
    return { width: 6, height: 6, borderRadius: '50%', background: map[variant] };
  },

  btnRow: { display: 'flex', gap: 6, justifyContent: 'flex-end' },
  btn: (variant) => ({
    height: 30, padding: '0 12px', borderRadius: 8,
    border: 0, cursor: 'pointer',
    fontSize: 12, fontWeight: 600, fontFamily: 'inherit',
    display: 'inline-flex', alignItems: 'center', gap: 5,
    background: variant === 'approve' ? 'var(--success)' :
                variant === 'reject' ? 'var(--danger)' :
                'var(--bg-elevated)',
    color: variant === 'approve' || variant === 'reject' ? '#fff' : 'var(--fg1)',
  }),
};

const DEPOSITS = [
  { id: '#DEP-04881', user: 'u_4821', level: 2, amount: 100,  ref: 'u_3019',  age: '2 мин',  status: 'pending' },
  { id: '#DEP-04880', user: 'u_9182', level: 1, amount: 20,   ref: '—',        age: '5 мин',  status: 'pending' },
  { id: '#DEP-04879', user: 'u_5512', level: 3, amount: 700,  ref: 'u_2210',  age: '8 мин',  status: 'pending' },
  { id: '#DEP-04878', user: 'u_7702', level: 4, amount: 2000, ref: 'u_1101',  age: '14 мин', status: 'pending' },
  { id: '#DEP-04877', user: 'u_3144', level: 2, amount: 100,  ref: '—',        age: '22 мин', status: 'approved' },
  { id: '#DEP-04876', user: 'u_8893', level: 1, amount: 20,   ref: 'u_1010',  age: '34 мин', status: 'approved' },
  { id: '#DEP-04875', user: 'u_2007', level: 3, amount: 700,  ref: 'u_4821',  age: '52 мин', status: 'approved' },
];

function DepositsTable() {
  const [filter, setFilter] = React.useState('pending');
  const [rows, setRows] = React.useState(DEPOSITS);
  const filtered = filter === 'all' ? rows : rows.filter(r => r.status === filter);

  const approve = id => setRows(rs => rs.map(r => r.id === id ? { ...r, status: 'approved' } : r));

  return (
    <div style={tableStyles.panel}>
      <div style={tableStyles.head}>
        <div>
          <div style={tableStyles.title}>Депозиты</div>
          <div style={tableStyles.sub}>Подтверждение запускает сплит 10 / 60 / 30 и обновляет очередь</div>
        </div>
      </div>
      <div style={tableStyles.filterBar}>
        <div style={tableStyles.seg}>
          <button style={tableStyles.segBtn(filter==='pending')} onClick={() => setFilter('pending')}>Ожидают</button>
          <button style={tableStyles.segBtn(filter==='approved')} onClick={() => setFilter('approved')}>Подтверждены</button>
          <button style={tableStyles.segBtn(filter==='all')} onClick={() => setFilter('all')}>Все</button>
        </div>
      </div>
      <table style={tableStyles.table}>
        <thead>
          <tr>
            <th style={tableStyles.th}>ID</th>
            <th style={tableStyles.th}>Пользователь</th>
            <th style={tableStyles.th}>Уровень</th>
            <th style={tableStyles.th}>Сумма</th>
            <th style={tableStyles.th}>Реферер</th>
            <th style={tableStyles.th}>Время</th>
            <th style={tableStyles.th}>Статус</th>
            <th style={{...tableStyles.th, textAlign: 'right'}}>Действие</th>
          </tr>
        </thead>
        <tbody>
          {filtered.map(r => (
            <tr key={r.id}>
              <td style={{...tableStyles.td, ...tableStyles.mono, color: 'var(--fg2)'}}>{r.id}</td>
              <td style={tableStyles.td}>{r.user}</td>
              <td style={tableStyles.td}>Level {r.level}</td>
              <td style={{...tableStyles.td, ...tableStyles.mono, fontWeight: 600}}>{r.amount.toLocaleString('ru-RU').replace(/,/g,' ')} USDT</td>
              <td style={{...tableStyles.td, color: 'var(--fg2)'}}>{r.ref}</td>
              <td style={{...tableStyles.td, color: 'var(--fg3)'}}>{r.age}</td>
              <td style={tableStyles.td}>
                <span style={tableStyles.pill(r.status)}>
                  <span style={tableStyles.pillDot(r.status)}/>
                  {r.status === 'pending' ? 'Ожидает' : 'Подтверждён'}
                </span>
              </td>
              <td style={tableStyles.td}>
                <div style={tableStyles.btnRow}>
                  {r.status === 'pending' ? (
                    <>
                      <button style={tableStyles.btn('approve')} onClick={() => approve(r.id)}><IcCheck size={12}/> Подтвердить</button>
                      <button style={tableStyles.btn('secondary')}>Детали</button>
                    </>
                  ) : (
                    <button style={tableStyles.btn('secondary')}>Детали</button>
                  )}
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

Object.assign(window, { DepositsTable, tableStyles });
