// ui_kits/dashboard/DepositSheet.jsx
const sheetStyles = {
  scrim: {
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.32)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    zIndex: 100,
    animation: 'fade 200ms ease',
  },
  sheet: {
    width: 440,
    background: '#fff',
    borderRadius: 20,
    padding: '24px',
    boxShadow: '0 24px 64px rgba(0,0,0,0.20)',
    position: 'relative',
  },
  close: {
    position: 'absolute', top: 16, right: 16,
    width: 32, height: 32, borderRadius: '50%',
    background: 'var(--bg-elevated)',
    border: 0, cursor: 'pointer', color: 'var(--fg2)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  title: {
    fontFamily: 'var(--font-display)',
    fontSize: 22, fontWeight: 600, letterSpacing: '-0.015em',
    color: 'var(--fg1)', marginBottom: 4,
  },
  sub: { fontSize: 13, color: 'var(--fg2)', marginBottom: 20 },

  tabs: {
    display: 'flex', background: 'var(--bg-elevated)', borderRadius: 11, padding: 3, gap: 3, marginBottom: 18,
  },
  tab: (active) => ({
    flex: 1, padding: '8px 0',
    border: 0, background: active ? '#fff' : 'transparent',
    boxShadow: active ? '0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)' : 'none',
    fontSize: 13, fontWeight: 600, color: 'var(--fg1)',
    borderRadius: 9, cursor: 'pointer', fontFamily: 'inherit',
  }),

  level: (active, color) => ({
    display: 'flex', alignItems: 'center', gap: 12,
    padding: '12px 14px',
    background: active ? '#fff' : '#fff',
    border: `1.5px solid ${active ? color : 'transparent'}`,
    boxShadow: active ? `0 0 0 4px ${color}1A` : 'inset 0 0 0 1px var(--hairline)',
    borderRadius: 14,
    cursor: 'pointer',
    transition: 'all var(--dur) var(--ease)',
  }),
  levelDot: (color) => ({ width: 10, height: 10, borderRadius: '50%', background: color }),
  levelName: { fontSize: 14, fontWeight: 600, color: 'var(--fg1)' },
  levelMeta: { fontSize: 12, color: 'var(--fg3)', marginTop: 1 },
  levelEntry: { marginLeft: 'auto', fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: 14, color: 'var(--fg1)' },

  notice: {
    display: 'flex', gap: 10, padding: '12px 14px',
    background: 'var(--accent-bg)', borderRadius: 12,
    color: 'var(--accent-press)', fontSize: 12, lineHeight: 1.4,
    marginTop: 14,
  },

  footer: { display: 'flex', gap: 8, marginTop: 20 },
  btn: (variant) => ({
    flex: 1, height: 44, borderRadius: 12,
    fontSize: 15, fontWeight: 600, fontFamily: 'inherit',
    border: 0, cursor: 'pointer',
    background: variant === 'primary' ? 'var(--accent)' : 'var(--bg-elevated)',
    color: variant === 'primary' ? '#fff' : 'var(--fg1)',
  }),
};

const LEVELS = [
  { level: 1, entry: 20,   payout: 30,    color: '#5AC8FA' },
  { level: 2, entry: 100,  payout: 150,   color: '#007AFF' },
  { level: 3, entry: 700,  payout: 1050,  color: '#5856D6' },
  { level: 4, entry: 2000, payout: 3000,  color: '#AF52DE' },
];

function DepositSheet({ open, onClose, defaultLevel = 2, balance = 1248 }) {
  const [tab, setTab] = React.useState('external');
  const [picked, setPicked] = React.useState(defaultLevel);
  if (!open) return null;

  const lvl = LEVELS.find(l => l.level === picked);
  const insufficient = tab === 'internal' && balance < lvl.entry;

  return (
    <div style={sheetStyles.scrim} onClick={onClose}>
      <div style={sheetStyles.sheet} onClick={e => e.stopPropagation()}>
        <button style={sheetStyles.close} onClick={onClose}><IcClose size={14}/></button>
        <div style={sheetStyles.title}>Активировать уровень</div>
        <div style={sheetStyles.sub}>Выберите тариф и способ оплаты</div>

        <div style={sheetStyles.tabs}>
          <button style={sheetStyles.tab(tab === 'external')} onClick={() => setTab('external')}>
            Внешний кошелёк
          </button>
          <button style={sheetStyles.tab(tab === 'internal')} onClick={() => setTab('internal')}>
            С баланса · {balance} USDT
          </button>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {LEVELS.map(l => (
            <div key={l.level} style={sheetStyles.level(picked === l.level, l.color)} onClick={() => setPicked(l.level)}>
              <span style={sheetStyles.levelDot(l.color)}/>
              <div>
                <div style={sheetStyles.levelName}>Level {l.level}</div>
                <div style={sheetStyles.levelMeta}>Цикл 150% · выплата {l.payout} USDT</div>
              </div>
              <div style={sheetStyles.levelEntry}>{l.entry} USDT</div>
            </div>
          ))}
        </div>

        <div style={sheetStyles.notice}>
          <IcInfo size={14}/>
          <span>
            Комиссия сервиса <strong>10%</strong> удерживается при активации.
            В очередь поступает <strong>90%</strong> суммы по правилу каскада.
          </span>
        </div>

        <div style={sheetStyles.footer}>
          <button style={sheetStyles.btn('secondary')} onClick={onClose}>Отмена</button>
          <button
            style={{...sheetStyles.btn('primary'), ...(insufficient ? { opacity: 0.5, cursor: 'not-allowed' } : {})}}
            disabled={insufficient}
            onClick={onClose}>
            {insufficient ? 'Недостаточно средств' :
             tab === 'external' ? `Сгенерировать адрес · ${lvl.entry} USDT` : `Списать ${lvl.entry} USDT`}
          </button>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { DepositSheet });

// resources/js/components/cascade/DepositSheet.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';

const props = withDefaults(
    defineProps<{
        open: boolean;
        defaultLevel?: number;
        balance?: number;
        walletAddress?: string;
        walletAmount?: number;
    }>(),
    {
        defaultLevel: 2,
        balance: 0,
    },
);

const emit = defineEmits<{
    close: [];
    confirm: [payload: { level: number; method: 'external' | 'internal' }];
}>();

type Method = 'external' | 'internal';

interface LevelOption {
    level: number;
    entry: number;
    payout: number;
    color: string;
}

const levels: LevelOption[] = [
    { level: 1, entry: 20, payout: 30, color: '#5AC8FA' },
    { level: 2, entry: 100, payout: 150, color: '#007AFF' },
    { level: 3, entry: 700, payout: 1050, color: '#5856D6' },
    { level: 4, entry: 2000, payout: 3000, color: '#AF52DE' },
];

const tab = ref<Method>('external');
const picked = ref<number>(props.defaultLevel);

watch(
    () => props.open,
    (isOpen) => {
        if (isOpen) {
            picked.value = props.defaultLevel;
            tab.value = 'external';
        }
    },
);

const pickedLevel = computed(
    () => levels.find((l) => l.level === picked.value)!,
);
const insufficient = computed(
    () => tab.value === 'internal' && props.balance < pickedLevel.value.entry,
);

const confirmLabel = computed(() => {
    if (insufficient.value) {
        return 'Недостаточно средств';
    }

    return tab.value === 'external'
        ? `Сгенерировать адрес · ${pickedLevel.value.entry} USDT`
        : `Списать ${pickedLevel.value.entry} USDT`;
});

function confirm() {
    if (insufficient.value) {
        return;
    }

    emit('confirm', { level: picked.value, method: tab.value });
}
</script>

<template>
    <Teleport to="body">
        <div
            v-if="open"
            class="fixed inset-0 z-[100] flex items-center justify-center"
            style="
                background: rgba(0, 0, 0, 0.32);
                animation: cascade-fade 200ms ease;
            "
            @click="emit('close')"
        >
            <div
                class="relative w-[440px] rounded-[20px] bg-white p-6"
                style="box-shadow: 0 24px 64px rgba(0, 0, 0, 0.2)"
                @click.stop
            >
                <button
                    class="absolute top-4 right-4 flex h-8 w-8 items-center justify-center rounded-full"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg2);
                    "
                    @click="emit('close')"
                >
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M6 6l12 12M18 6l-12 12" />
                    </svg>
                </button>

                <!-- Step 2: wallet address display after external deposit created -->
                <template v-if="walletAddress">
                    <div
                        class="mb-2 text-[22px] font-semibold tracking-[-0.015em]"
                        style="
                            color: var(--c-fg1);
                            font-family: var(--c-font-display);
                        "
                    >
                        Адрес для оплаты
                    </div>
                    <div
                        class="mb-5 text-[13px] leading-relaxed"
                        style="color: var(--c-fg2)"
                    >
                        Отправьте ровно
                        <strong style="color: var(--c-fg1)"
                            >{{ walletAmount }} USDT (TRC-20)</strong
                        >
                        на адрес ниже. После подтверждения транзакции администратор активирует уровень.
                    </div>
                    <div
                        class="mb-5 rounded-[14px] px-4 py-4 text-center"
                        style="background: var(--c-bg-elevated)"
                    >
                        <div
                            class="break-all text-sm font-semibold"
                            style="
                                font-family: var(--c-font-mono);
                                color: var(--c-fg1);
                                word-break: break-all;
                            "
                        >
                            {{ walletAddress }}
                        </div>
                    </div>
                    <div
                        class="mb-5 flex gap-3.5 rounded-xl px-4 py-3.5"
                        style="background: var(--c-warning-bg)"
                    >
                        <svg
                            class="shrink-0"
                            width="15"
                            height="15"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="var(--c-warning)"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                        >
                            <circle cx="12" cy="12" r="9" />
                            <path d="M12 8v.01M12 11v5" />
                        </svg>
                        <div
                            class="text-xs leading-relaxed"
                            style="color: #8c5400"
                        >
                            Отправляйте только USDT в сети TRC-20. После
                            отправки средства будут зачислены администратором
                            вручную.
                        </div>
                    </div>
                    <button
                        class="h-11 w-full rounded-xl text-[15px] font-semibold text-white"
                        style="background: var(--c-accent)"
                        @click="emit('close')"
                    >
                        Понятно
                    </button>
                </template>

                <!-- Step 1: level & method selection -->
                <template v-else>
                <div
                    class="mb-1 text-[22px] font-semibold tracking-[-0.015em]"
                    style="
                        color: var(--c-fg1);
                        font-family: var(--c-font-display);
                    "
                >
                    Активировать уровень
                </div>
                <div class="mb-5 text-[13px]" style="color: var(--c-fg2)">
                    Выберите тариф и способ оплаты
                </div>

                <div
                    class="mb-[18px] flex gap-0.5 rounded-[11px] p-[3px]"
                    style="background: var(--c-bg-elevated)"
                >
                    <button
                        class="flex-1 rounded-[9px] py-2 text-[13px] font-semibold transition-colors"
                        :style="
                            tab === 'external'
                                ? 'background: #fff; color: var(--c-fg1); box-shadow: 0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)'
                                : 'background: transparent; color: var(--c-fg1)'
                        "
                        @click="tab = 'external'"
                    >
                        Внешний кошелёк
                    </button>
                    <button
                        class="flex-1 rounded-[9px] py-2 text-[13px] font-semibold transition-colors"
                        :style="
                            tab === 'internal'
                                ? 'background: #fff; color: var(--c-fg1); box-shadow: 0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)'
                                : 'background: transparent; color: var(--c-fg1)'
                        "
                        @click="tab = 'internal'"
                    >
                        С баланса · {{ balance }} USDT
                    </button>
                </div>

                <div class="flex flex-col gap-2">
                    <button
                        v-for="l in levels"
                        :key="l.level"
                        class="flex items-center gap-3 rounded-[14px] px-3.5 py-3 text-left transition-all duration-[160ms]"
                        :style="
                            picked === l.level
                                ? `border: 1.5px solid ${l.color}; box-shadow: 0 0 0 4px ${l.color}1A`
                                : 'border: 1.5px solid transparent; box-shadow: inset 0 0 0 1px var(--c-hairline)'
                        "
                        @click="picked = l.level"
                    >
                        <span
                            class="h-2.5 w-2.5 rounded-full"
                            :style="{ background: l.color }"
                        />
                        <div>
                            <div
                                class="text-sm font-semibold"
                                style="color: var(--c-fg1)"
                            >
                                Level {{ l.level }}
                            </div>
                            <div
                                class="mt-px text-xs"
                                style="color: var(--c-fg3)"
                            >
                                Цикл 150% · выплата {{ l.payout }} USDT
                            </div>
                        </div>
                        <div
                            class="ml-auto text-sm font-semibold"
                            style="
                                color: var(--c-fg1);
                                font-family: var(--c-font-mono);
                            "
                        >
                            {{ l.entry }} USDT
                        </div>
                    </button>
                </div>

                <div
                    class="mt-3.5 flex gap-2.5 rounded-xl px-3.5 py-3 text-xs leading-snug"
                    style="
                        background: var(--c-accent-bg);
                        color: var(--c-accent-press);
                    "
                >
                    <svg
                        class="shrink-0"
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <circle cx="12" cy="12" r="9" />
                        <path d="M12 8v.01M12 11v5" />
                    </svg>
                    <span>
                        Комиссия сервиса <strong>10%</strong> удерживается при
                        активации. В очередь поступает
                        <strong>90%</strong> суммы по правилу каскада.
                    </span>
                </div>

                <div class="mt-5 flex gap-2">
                    <button
                        class="h-11 flex-1 rounded-xl text-[15px] font-semibold"
                        style="
                            background: var(--c-bg-elevated);
                            color: var(--c-fg1);
                        "
                        @click="emit('close')"
                    >
                        Отмена
                    </button>
                    <button
                        :disabled="insufficient"
                        class="h-11 flex-1 rounded-xl text-[15px] font-semibold text-white"
                        style="background: var(--c-accent)"
                        :class="
                            insufficient ? 'cursor-not-allowed opacity-50' : ''
                        "
                        @click="confirm"
                    >
                        {{ confirmLabel }}
                    </button>
                </div>
                </template>
            </div>
        </div>
    </Teleport>
</template>

<style scoped>
@keyframes cascade-fade {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}
</style>
