// ui_kits/dashboard/QueueCard.jsx
const queueColors = {
  1: 'var(--level-1)',
  2: 'var(--level-2)',
  3: 'var(--level-3)',
  4: 'var(--level-4)',
};

const queueStyles = {
  card: {
    background: '#fff',
    borderRadius: 20,
    padding: '20px 22px 22px',
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    display: 'flex', flexDirection: 'column', gap: 16,
    transition: 'transform var(--dur) var(--ease)',
  },
  head: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' },
  levelTag: (level) => ({
    display: 'inline-flex', alignItems: 'center', gap: 6,
    fontSize: 11, fontWeight: 700, letterSpacing: '0.06em',
    color: 'var(--fg2)', textTransform: 'uppercase',
  }),
  dot: (level) => ({
    width: 8, height: 8, borderRadius: '50%', background: queueColors[level],
  }),
  ratio: {
    fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums',
    fontSize: 13, fontWeight: 600, color: 'var(--fg2)',
  },
  amount: {
    fontFamily: 'var(--font-display)',
    fontSize: 28, fontWeight: 700, letterSpacing: '-0.02em',
    color: 'var(--fg1)',
    fontVariantNumeric: 'tabular-nums',
  },
  amountUnit: { color: 'var(--fg3)', fontSize: 15, fontWeight: 500, marginLeft: 6 },
  rowMeta: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    fontSize: 12, color: 'var(--fg3)',
  },

  cellsRow: { display: 'flex', gap: 5 },
  cell: (filled, bonus) => ({
    flex: 1, height: 32, borderRadius: 8,
    background: filled ? (bonus ? '#FFCC00' : 'var(--success)') : 'var(--cell-empty-bg)',
    boxShadow: filled ? 'none' : 'inset 0 0 0 1px var(--cell-empty-ring)',
    transition: 'all var(--dur) var(--ease)',
  }),

  timer: (status) => ({
    fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums',
    fontSize: 13, fontWeight: 500,
    color: status === 'ready' ? 'var(--success)' :
           status === 'locked' ? 'var(--accent)' :
           status === 'inactive' ? 'var(--fg3)' : 'var(--fg2)',
    display: 'inline-flex', alignItems: 'center', gap: 6,
  }),

  actionRow: { display: 'flex', gap: 8, marginTop: 4 },
  btn: (variant) => ({
    flex: 1, height: 36,
    borderRadius: 10,
    fontFamily: 'var(--font-text)',
    fontSize: 13, fontWeight: 600,
    border: 0, cursor: 'pointer',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    background: variant === 'primary' ? 'var(--accent)' :
                variant === 'success' ? 'var(--success)' :
                'var(--bg-elevated)',
    color: variant === 'primary' || variant === 'success' ? '#fff' : 'var(--fg1)',
    transition: 'transform var(--dur) var(--ease), background var(--dur) var(--ease)',
  }),
  btnDisabled: {
    background: 'var(--bg-elevated)', color: 'var(--fg3)', cursor: 'not-allowed',
  },

  toggleRow: {
    display: 'flex', alignItems: 'center', gap: 10,
    padding: '8px 0 0', borderTop: '1px solid var(--hairline-soft)',
    marginTop: 2, paddingTop: 12,
  },
  toggleLabel: { fontSize: 13, color: 'var(--fg2)', flex: 1 },
  toggle: (on) => ({
    width: 36, height: 22,
    background: on ? 'var(--success)' : 'var(--neutral-bg)',
    borderRadius: 999, position: 'relative',
    cursor: 'pointer',
    transition: 'background var(--dur) var(--ease)',
  }),
  toggleKnob: (on) => ({
    position: 'absolute', top: 2, left: 2,
    width: 18, height: 18, borderRadius: '50%', background: '#fff',
    boxShadow: '0 2px 4px rgba(0,0,0,0.15)',
    transform: on ? 'translateX(14px)' : 'translateX(0)',
    transition: 'transform var(--dur) var(--ease)',
  }),
};

function fmt(n) {
  return n.toLocaleString('ru-RU').replace(/,/g, ' ');
}

function QueueCard({ level, entry, payout, filled, status, timer, autoReinvest, onActivate, onReinvest, onUpgrade, onToggleAuto }) {
  const ratio = `${filled} / 5`;
  const isReady = status === 'ready';
  const isInactive = status === 'inactive';
  const isLocked = status === 'locked';

  return (
    <div style={queueStyles.card}>
      <div style={queueStyles.head}>
        <div style={queueStyles.levelTag(level)}>
          <span style={queueStyles.dot(level)}/>Level {level}
        </div>
        <div style={queueStyles.ratio}>{isInactive ? 'не активен' : ratio}</div>
      </div>

      <div>
        <div style={queueStyles.amount}>
          {fmt(entry)}<span style={queueStyles.amountUnit}>USDT</span>
        </div>
        <div style={{ fontSize: 12, color: 'var(--fg3)', marginTop: 2 }}>
          Выплата за цикл: {fmt(payout)} USDT
        </div>
      </div>

      <div style={queueStyles.cellsRow}>
        {Array.from({ length: 5 }).map((_, i) => (
          <div key={i} style={queueStyles.cell(i < filled, false)}/>
        ))}
      </div>

      <div style={queueStyles.rowMeta}>
        <div style={queueStyles.timer(status)}>
          {isReady && <><IcCheck size={14}/> Готов к выводу</>}
          {isLocked && <><IcLock size={12}/> Замок: {timer}</>}
          {isInactive && <>Не активирован</>}
          {status === 'pending' && <>В ожидании: {timer}</>}
        </div>
      </div>

      <div style={queueStyles.actionRow}>
        {isInactive ? (
          <button style={queueStyles.btn('primary')} onClick={onActivate}>
            <IcPlus size={14}/> Активировать
          </button>
        ) : (
          <>
            <button
              style={isReady ? queueStyles.btn('success') : { ...queueStyles.btn('secondary'), ...(isLocked ? queueStyles.btnDisabled : {}) }}
              onClick={!isLocked ? onReinvest : null}
              disabled={isLocked}>
              <IcRefresh size={13}/> Реинвест
            </button>
            <button style={queueStyles.btn('secondary')} onClick={onUpgrade}>
              <IcArrowUp size={13}/> Апгрейд
            </button>
          </>
        )}
      </div>

      {!isInactive && (
        <div style={queueStyles.toggleRow}>
          <span style={queueStyles.toggleLabel}>Авто-вход после цикла</span>
          <div style={queueStyles.toggle(autoReinvest)} onClick={onToggleAuto}>
            <div style={queueStyles.toggleKnob(autoReinvest)}/>
          </div>
        </div>
      )}
    </div>
  );
}

Object.assign(window, { QueueCard });

// resources/js/components/cascade/QueueCard.vue
<script setup lang="ts">
import { computed } from 'vue';

type QueueStatus = 'ready' | 'locked' | 'inactive' | 'pending';

const props = defineProps<{
    level: number;
    entry: number;
    payout: number;
    filled: number;
    status: QueueStatus;
    timer?: string | null;
    autoReinvest: boolean;
}>();

const emit = defineEmits<{
    activate: [];
    reinvest: [];
    upgrade: [];
    toggleAuto: [];
}>();

const levelColors: Record<number, string> = {
    1: 'var(--c-level-1)',
    2: 'var(--c-level-2)',
    3: 'var(--c-level-3)',
    4: 'var(--c-level-4)',
};

const isReady = computed(() => props.status === 'ready');
const isInactive = computed(() => props.status === 'inactive');
const isLocked = computed(() => props.status === 'locked');
const isPending = computed(() => props.status === 'pending');

const ratio = computed(() => `${props.filled} / 5`);

const timerColor = computed(() => {
    switch (props.status) {
        case 'ready':
            return 'var(--c-success)';
        case 'locked':
            return 'var(--c-accent)';
        case 'inactive':
            return 'var(--c-fg3)';
        default:
            return 'var(--c-fg2)';
    }
});

function fmt(n: number): string {
    return n.toLocaleString('ru-RU').replace(/,/g, ' ');
}
</script>

<template>
    <div
        class="flex flex-col gap-4 rounded-[20px] bg-[var(--c-bg-card)] px-[22px] pt-5 pb-[22px]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <!-- head -->
        <div class="flex items-start justify-between">
            <div
                class="inline-flex items-center gap-1.5 text-[11px] font-bold tracking-[0.06em] uppercase"
                style="color: var(--c-fg2)"
            >
                <span
                    class="h-2 w-2 rounded-full"
                    :style="{ background: levelColors[level] }"
                />
                Level {{ level }}
            </div>
            <div
                class="text-[13px] font-semibold"
                style="
                    color: var(--c-fg2);
                    font-family: var(--c-font-mono);
                    font-variant-numeric: tabular-nums;
                "
            >
                {{ isInactive ? 'не активен' : ratio }}
            </div>
        </div>

        <!-- amount -->
        <div>
            <div
                class="text-[28px] font-bold tracking-[-0.02em]"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-display);
                    font-variant-numeric: tabular-nums;
                "
            >
                {{ fmt(entry)
                }}<span
                    class="ml-1.5 text-[15px] font-medium"
                    style="color: var(--c-fg3)"
                    >USDT</span
                >
            </div>
            <div class="mt-0.5 text-xs" style="color: var(--c-fg3)">
                Выплата за цикл: {{ fmt(payout) }} USDT
            </div>
        </div>

        <!-- cells -->
        <div class="flex gap-[5px]">
            <div
                v-for="i in 5"
                :key="i"
                class="h-8 flex-1 rounded-lg transition-all duration-[160ms]"
                :style="
                    i <= filled
                        ? 'background: var(--c-success)'
                        : 'background: var(--c-bg-elevated); box-shadow: inset 0 0 0 1px var(--c-hairline)'
                "
            />
        </div>

        <!-- status row -->
        <div class="flex items-center justify-between text-xs">
            <div
                class="inline-flex items-center gap-1.5 text-[13px] font-medium"
                :style="{ color: timerColor }"
            >
                <template v-if="isReady">
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M5 12l5 5 9-11" />
                    </svg>
                    Готов к выводу
                </template>
                <template v-else-if="isLocked">
                    <svg
                        width="12"
                        height="12"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <rect x="5" y="11" width="14" height="9" rx="2" />
                        <path d="M8 11V7a4 4 0 0 1 8 0v4" />
                    </svg>
                    Замок: {{ timer }}
                </template>
                <template v-else-if="isInactive">Не активирован</template>
                <template v-else-if="isPending"
                    >В ожидании: {{ timer }}</template
                >
            </div>
        </div>

        <!-- actions -->
        <div class="mt-1 flex gap-2">
            <button
                v-if="isInactive"
                class="flex h-9 flex-1 items-center justify-center gap-1.5 rounded-[10px] text-[13px] font-semibold text-white transition-transform duration-[160ms] active:scale-95"
                style="background: var(--c-accent)"
                @click="emit('activate')"
            >
                <svg
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                >
                    <path d="M12 5v14M5 12h14" />
                </svg>
                Активировать
            </button>
            <template v-else>
                <button
                    :disabled="isLocked"
                    class="flex h-9 flex-1 items-center justify-center gap-1.5 rounded-[10px] text-[13px] font-semibold transition-transform duration-[160ms]"
                    :class="isLocked ? 'cursor-not-allowed' : 'active:scale-95'"
                    :style="
                        isReady
                            ? 'background: var(--c-success); color: #fff'
                            : isLocked
                              ? 'background: var(--c-bg-elevated); color: var(--c-fg3)'
                              : 'background: var(--c-bg-elevated); color: var(--c-fg1)'
                    "
                    @click="!isLocked && emit('reinvest')"
                >
                    <svg
                        width="13"
                        height="13"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M21 12a9 9 0 1 1-3-6.7" />
                        <path d="M21 4v5h-5" />
                    </svg>
                    Реинвест
                </button>
                <button
                    class="flex h-9 flex-1 items-center justify-center gap-1.5 rounded-[10px] text-[13px] font-semibold transition-transform duration-[160ms] active:scale-95"
                    style="
                        background: var(--c-bg-elevated);
                        color: var(--c-fg1);
                    "
                    @click="emit('upgrade')"
                >
                    <svg
                        width="13"
                        height="13"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M12 19V5M6 11l6-6 6 6" />
                    </svg>
                    Апгрейд
                </button>
            </template>
        </div>

        <!-- auto toggle -->
        <div
            v-if="!isInactive"
            class="mt-0.5 flex items-center gap-2.5 pt-3"
            style="border-top: 1px solid var(--c-hairline-soft)"
        >
            <span class="flex-1 text-[13px]" style="color: var(--c-fg2)"
                >Авто-вход после цикла</span
            >
            <button
                class="relative h-[22px] w-9 rounded-full transition-colors duration-[160ms]"
                :style="
                    autoReinvest
                        ? 'background: var(--c-success)'
                        : 'background: #e5e5ea'
                "
                @click="emit('toggleAuto')"
            >
                <span
                    class="absolute top-0.5 left-0.5 h-[18px] w-[18px] rounded-full bg-[var(--c-knob)] transition-transform duration-[160ms]"
                    style="box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15)"
                    :style="
                        autoReinvest
                            ? 'transform: translateX(14px)'
                            : 'transform: translateX(0)'
                    "
                />
            </button>
        </div>
    </div>
</template>
