// resources/js/components/cascade/HistoryFeed.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

type HistoryKind = 'ref' | 'cell' | 'reinv' | 'hold' | 'deposit';
type AmountSign = 'pos' | 'neg' | 'gold' | 'warn' | 'neu';

export interface HistoryRow {
    kind: HistoryKind;
    title: string;
    sub: string;
    amount: string;
    sign: AmountSign;
    time: string;
}

const props = withDefaults(
    defineProps<{
        rows?: HistoryRow[];
    }>(),
    {
        rows: () => [],
    },
);

type FilterKey = 'all' | 'income' | 'out' | 'hold';

const filter = ref<FilterKey>('all');

const filters: { key: FilterKey; label: string }[] = [
    { key: 'all', label: 'Все' },
    { key: 'income', label: 'Доходы' },
    { key: 'out', label: 'Расходы' },
    { key: 'hold', label: 'Холд' },
];

const visibleRows = computed(() => {
    if (filter.value === 'all') {
        return props.rows;
    }

    return props.rows.filter((row) => {
        switch (filter.value) {
            case 'income':
                return row.sign === 'pos' || row.sign === 'gold';
            case 'out':
                return row.sign === 'neg';
            case 'hold':
                return row.sign === 'warn' || row.kind === 'hold';
            default:
                return true;
        }
    });
});

const iconBg: Record<HistoryKind, [string, string]> = {
    ref: ['var(--c-success-bg)', 'var(--c-success)'],
    cell: ['var(--c-gold-bg)', 'var(--c-gold)'],
    reinv: ['var(--c-danger-bg)', 'var(--c-danger)'],
    hold: ['var(--c-warning-bg)', 'var(--c-warning)'],
    deposit: ['var(--c-accent-bg)', 'var(--c-accent)'],
};

const iconGlyph: Record<HistoryKind, string> = {
    ref: '+',
    cell: '●',
    reinv: '↻',
    hold: '⏳',
    deposit: '↓',
};

function amountColor(sign: AmountSign): string {
    switch (sign) {
        case 'pos':
            return 'var(--c-success)';
        case 'neg':
            return 'var(--c-danger)';
        case 'gold':
            return 'var(--c-gold)';
        case 'warn':
            return 'var(--c-warning)';
        default:
            return 'var(--c-fg1)';
    }
}
</script>

<template>
    <div
        class="overflow-hidden rounded-[20px] bg-[var(--c-bg-card)]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-center gap-3 px-[22px] pt-[18px] pb-3.5">
            <div
                class="text-[17px] font-semibold tracking-[-0.01em]"
                style="color: var(--c-fg1); font-family: var(--c-font-display)"
            >
                История операций
            </div>
            <div
                class="ml-auto inline-flex gap-0.5 rounded-[9px] p-0.5"
                style="background: var(--c-bg-elevated)"
            >
                <button
                    v-for="f in filters"
                    :key="f.key"
                    class="rounded-[7px] px-[11px] py-[5px] text-xs font-semibold transition-colors"
                    :style="
                        filter === f.key
                            ? 'background: var(--c-bg-active); color: var(--c-fg1); box-shadow: 0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)'
                            : 'background: transparent; color: var(--c-fg1)'
                    "
                    @click="filter = f.key"
                >
                    {{ f.label }}
                </button>
            </div>
        </div>

        <div
            v-if="visibleRows.length === 0"
            class="px-[22px] py-10 text-center text-[13px]"
            style="
                color: var(--c-fg3);
                border-top: 1px solid var(--c-hairline-soft);
            "
        >
            Операций пока нет
        </div>

        <div
            v-for="(row, i) in visibleRows"
            :key="i"
            class="flex items-center gap-3.5 px-[22px] py-3"
            style="border-top: 1px solid var(--c-hairline-soft)"
        >
            <div
                class="flex h-8 w-8 shrink-0 items-center justify-center rounded-[10px]"
                :style="{
                    background: iconBg[row.kind][0],
                    color: iconBg[row.kind][1],
                }"
            >
                {{ iconGlyph[row.kind] }}
            </div>
            <div class="min-w-0 flex-1">
                <div
                    class="text-[13px] font-semibold"
                    style="color: var(--c-fg1)"
                >
                    {{ row.title }}
                </div>
                <div class="mt-0.5 text-xs" style="color: var(--c-fg3)">
                    {{ row.sub }}
                </div>
            </div>
            <div
                class="text-sm font-semibold"
                :style="{
                    color: amountColor(row.sign),
                    fontFamily: 'var(--c-font-mono)',
                    fontVariantNumeric: 'tabular-nums',
                }"
            >
                {{ row.amount }} USDT
            </div>
            <div
                class="text-[11px]"
                style="color: var(--c-fg3); font-family: var(--c-font-mono)"
            >
                {{ row.time }}
            </div>
        </div>
    </div>
</template>

// ui_kits/dashboard/HistoryFeed.jsx
const historyStyles = {
  wrap: {
    background: '#fff',
    borderRadius: 20,
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    overflow: 'hidden',
  },
  header: {
    padding: '18px 22px 14px',
    display: 'flex', alignItems: 'center', gap: 12,
  },
  title: {
    fontFamily: 'var(--font-display)',
    fontSize: 17, fontWeight: 600, letterSpacing: '-0.01em', color: 'var(--fg1)',
  },
  filter: {
    display: 'inline-flex', background: 'var(--bg-elevated)', borderRadius: 9, padding: 2, marginLeft: 'auto', gap: 2,
  },
  filterBtn: (active) => ({
    border: 0, background: active ? '#fff' : 'transparent',
    boxShadow: active ? '0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)' : 'none',
    padding: '5px 11px', fontSize: 12, fontWeight: 600,
    color: 'var(--fg1)', borderRadius: 7, cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  row: {
    display: 'flex', alignItems: 'center', gap: 14,
    padding: '12px 22px',
    borderTop: '1px solid var(--hairline-soft)',
  },
  ico: (kind) => {
    const map = {
      ref:     ['var(--success-bg)', 'var(--success)'],
      cell:    ['var(--gold-bg)',    'var(--gold)'],
      reinv:   ['var(--danger-bg)',  'var(--danger)'],
      hold:    ['var(--warning-bg)', 'var(--warning)'],
      deposit: ['var(--accent-bg)',  'var(--accent)'],
    };
    const [bg, fg] = map[kind] || ['var(--bg-elevated)', 'var(--fg2)'];
    return {
      width: 32, height: 32, borderRadius: 10, flexShrink: 0,
      background: bg, color: fg,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    };
  },
  body: { flex: 1, minWidth: 0 },
  title2: { fontSize: 13, fontWeight: 600, color: 'var(--fg1)' },
  sub: { fontSize: 12, color: 'var(--fg3)', marginTop: 2 },
  amt: (sign) => ({
    fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums',
    fontSize: 14, fontWeight: 600,
    color: sign === 'pos' ? 'var(--success)' :
           sign === 'neg' ? 'var(--danger)' :
           sign === 'gold' ? 'var(--gold)' :
           sign === 'warn' ? 'var(--warning)' : 'var(--fg1)',
  }),
  time: { fontSize: 11, color: 'var(--fg3)', fontFamily: 'var(--font-mono)' },
};

const ROWS = [
  { kind: 'ref',     title: 'Реферальный бонус',     sub: 'от user_4821 · Level 2', amount: '+60,00', sign: 'pos',  time: '14:23' },
  { kind: 'cell',    title: 'Закрашена ячейка',      sub: 'Очередь 700 · ячейка 3 из 5', amount: '+210,00', sign: 'gold', time: '13:55' },
  { kind: 'cell',    title: 'Закрашена ячейка',      sub: 'Очередь 100 · ячейка 2 из 5', amount: '+30,00',  sign: 'gold', time: '12:01' },
  { kind: 'hold',    title: 'Заявка на вывод · холд', sub: 'Освободится через 36 ч 12 мин', amount: '−1 050,00', sign: 'warn', time: 'вчера' },
  { kind: 'reinv',   title: 'Реинвест',              sub: 'Каскад в Очередь 100', amount: '−90,00',  sign: 'neg', time: 'вчера' },
  { kind: 'deposit', title: 'Депозит подтверждён',    sub: 'Level 3 · 700 USDT', amount: '+0,00',   sign: 'neu', time: '2 дн' },
  { kind: 'ref',     title: 'Реферальный бонус',     sub: 'от user_9182 · Level 1', amount: '+12,00', sign: 'pos', time: '2 дн' },
];

const ICON_FOR = {
  ref:     '+',
  cell:    '●',
  reinv:   '↻',
  hold:    '⏳',
  deposit: '↓',
};

function HistoryFeed() {
  const [filter, setFilter] = React.useState('all');
  return (
    <div style={historyStyles.wrap}>
      <div style={historyStyles.header}>
        <div style={historyStyles.title}>История операций</div>
        <div style={historyStyles.filter}>
          {['all','Доходы','Расходы','Холд'].map((k, i) => {
            const key = ['all','income','out','hold'][i];
            const lbl = i === 0 ? 'Все' : k;
            return (
              <button key={key} style={historyStyles.filterBtn(filter === key)} onClick={() => setFilter(key)}>{lbl}</button>
            );
          })}
        </div>
      </div>
      {ROWS.map((r, i) => (
        <div key={i} style={historyStyles.row}>
          <div style={historyStyles.ico(r.kind)}>{ICON_FOR[r.kind]}</div>
          <div style={historyStyles.body}>
            <div style={historyStyles.title2}>{r.title}</div>
            <div style={historyStyles.sub}>{r.sub}</div>
          </div>
          <div style={historyStyles.amt(r.sign)}>{r.amount} USDT</div>
          <div style={historyStyles.time}>{r.time}</div>
        </div>
      ))}
    </div>
  );
}

Object.assign(window, { HistoryFeed });
