// resources/js/components/cascade/partner/BonusStats.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
    defineProps<{
        totalEarned?: number;
        filledCells?: number;
        maxLevel?: number;
        activeCount?: number;
    }>(),
    {
        totalEarned: 0,
        filledCells: 0,
        maxLevel: 1,
        activeCount: 0,
    },
);

const friends = computed(() =>
    Array.from({ length: 5 }, (_, i) => i < props.activeCount),
);

const cellsPct = computed(() => Math.round((props.filledCells / 5) * 100));

function fmt(n: number): string {
    return n.toLocaleString('ru-RU', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    });
}
</script>

<template>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div
            class="flex flex-col gap-1.5 rounded-[18px] bg-[var(--c-bg-card)] px-[22px] py-5"
            style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
        >
            <div
                class="text-[12px] font-semibold tracking-[0.01em]"
                style="color: var(--c-fg3)"
            >
                Заработано бонусов · всего
            </div>
            <div
                class="text-[30px] font-bold tracking-[-0.02em]"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-display);
                    font-variant-numeric: tabular-nums;
                "
            >
                {{ fmt(props.totalEarned) }}
                <span
                    class="text-[16px] font-medium"
                    style="color: var(--c-fg3)"
                    >USDT</span
                >
            </div>
            <div class="text-[12px]" style="color: var(--c-fg2)">
                Реферальные бонусы за всё время
            </div>
        </div>

        <div
            class="flex flex-col gap-1.5 rounded-[18px] bg-[var(--c-bg-card)] px-[22px] py-5"
            style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
        >
            <div
                class="text-[12px] font-semibold tracking-[0.01em]"
                style="color: var(--c-fg3)"
            >
                Бонусных ячеек
            </div>
            <div
                class="text-[30px] font-bold tracking-[-0.02em]"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-display);
                    font-variant-numeric: tabular-nums;
                "
            >
                {{ props.filledCells }} / 5
            </div>
            <div class="text-[12px]" style="color: var(--c-fg2)">
                На Level {{ props.maxLevel }} (текущий активный пакет)
            </div>
            <div
                class="mt-2 h-1.5 overflow-hidden rounded-[3px]"
                style="background: var(--c-cell-empty-bg)"
            >
                <div
                    class="h-full rounded-[3px]"
                    :style="{
                        width: cellsPct + '%',
                        background: 'var(--c-success)',
                    }"
                />
            </div>
        </div>

        <div
            class="flex flex-col gap-1.5 rounded-[18px] bg-[var(--c-bg-card)] px-[22px] py-5"
            style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
        >
            <div
                class="text-[12px] font-semibold tracking-[0.01em]"
                style="color: var(--c-fg3)"
            >
                Правило 5 друзей
            </div>
            <div
                class="text-[30px] font-bold tracking-[-0.02em]"
                style="
                    color: var(--c-fg1);
                    font-family: var(--c-font-display);
                    font-variant-numeric: tabular-nums;
                "
            >
                {{ props.activeCount }} / 5
            </div>
            <div class="text-[12px]" style="color: var(--c-fg2)">
                <template v-if="props.activeCount < 5">
                    Пригласите ещё {{ 5 - props.activeCount }}, чтобы закрыть
                    цикл
                </template>
                <template v-else>Цикл закрыт ✓</template>
            </div>
            <div class="mt-2 flex gap-1">
                <div
                    v-for="(filled, i) in friends"
                    :key="i"
                    class="h-2.5 flex-1 rounded-[5px]"
                    :style="
                        filled
                            ? 'background: var(--c-success)'
                            : 'background: var(--c-cell-empty-bg); box-shadow: inset 0 0 0 1px var(--c-cell-empty-ring)'
                    "
                />
            </div>
        </div>
    </div>
</template>

// ui_kits/partner/BonusStats.jsx
const bonusStyles = {
  grid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 },
  card: {
    background: '#fff', borderRadius: 18, padding: '20px 22px',
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    display: 'flex', flexDirection: 'column', gap: 6,
  },
  label: { fontSize: 12, color: 'var(--fg3)', fontWeight: 600, letterSpacing: '0.01em' },
  value: {
    fontFamily: 'var(--font-display)',
    fontSize: 30, fontWeight: 700, letterSpacing: '-0.02em', color: 'var(--fg1)',
    fontVariantNumeric: 'tabular-nums',
  },
  sub: { fontSize: 12, color: 'var(--fg2)' },

  progressTrack: {
    height: 6, background: 'var(--cell-empty-bg)', borderRadius: 3,
    overflow: 'hidden', marginTop: 8,
  },
  progressFill: (pct) => ({
    height: '100%', width: `${pct}%`,
    background: 'var(--success)', borderRadius: 3,
  }),
  friends: {
    display: 'flex', gap: 4, marginTop: 8,
  },
  dot: (filled) => ({
    flex: 1, height: 10, borderRadius: 5,
    background: filled ? 'var(--success)' : 'var(--cell-empty-bg)',
    boxShadow: filled ? 'none' : 'inset 0 0 0 1px var(--cell-empty-ring)',
  }),
};

function BonusStats() {
  return (
    <div style={bonusStyles.grid}>
      <div style={bonusStyles.card}>
        <div style={bonusStyles.label}>Заработано бонусов · всего</div>
        <div style={bonusStyles.value}>284,00 <span style={{ color: 'var(--fg3)', fontSize: 16, fontWeight: 500 }}>USDT</span></div>
        <div style={bonusStyles.sub}>+ 60 USDT за последнюю неделю</div>
      </div>
      <div style={bonusStyles.card}>
        <div style={bonusStyles.label}>Бонусных ячеек</div>
        <div style={bonusStyles.value}>3 / 5</div>
        <div style={bonusStyles.sub}>На Level 2 (текущий активный пакет)</div>
        <div style={bonusStyles.progressTrack}><div style={bonusStyles.progressFill(60)}/></div>
      </div>
      <div style={bonusStyles.card}>
        <div style={bonusStyles.label}>Правило 5 друзей</div>
        <div style={bonusStyles.value}>3 / 5</div>
        <div style={bonusStyles.sub}>Пригласите ещё 2, чтобы закрыть цикл</div>
        <div style={bonusStyles.friends}>
          <div style={bonusStyles.dot(true)}/>
          <div style={bonusStyles.dot(true)}/>
          <div style={bonusStyles.dot(true)}/>
          <div style={bonusStyles.dot(false)}/>
          <div style={bonusStyles.dot(false)}/>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { BonusStats });
