// resources/js/components/cascade/partner/RefLinkCard.vue
<script setup lang="ts">
import { ref } from 'vue';

const props = withDefaults(
    defineProps<{
        active?: boolean;
        link?: string;
    }>(),
    {
        active: true,
        link: '',
    },
);

const copied = ref(false);

function copy(): void {
    if (props.link) {
        navigator.clipboard.writeText(props.link).catch(() => {});
    }

    copied.value = true;
    setTimeout(() => {
        copied.value = false;
    }, 1400);
}
</script>

<template>
    <div
        class="flex flex-col gap-4 rounded-[20px] bg-white px-6 py-[22px]"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-center gap-3">
            <div
                class="text-[18px] font-semibold tracking-[-0.01em]"
                style="color: var(--c-fg1); font-family: var(--c-font-display)"
            >
                Реферальная ссылка
            </div>
            <div
                class="ml-auto inline-flex items-center gap-1.5 rounded-full px-[9px] py-[3px] text-[11px] font-semibold"
                :style="
                    active
                        ? 'background: var(--c-success-bg); color: #1a6e34'
                        : 'background: var(--c-neutral-bg); color: var(--c-fg2)'
                "
            >
                <span
                    class="h-1.5 w-1.5 rounded-full"
                    :style="{
                        background: active
                            ? 'var(--c-success)'
                            : 'var(--c-neutral)',
                    }"
                />
                {{ active ? 'Активна' : 'Неактивна' }}
            </div>
        </div>

        <div
            class="flex h-12 items-center gap-2.5 rounded-xl pr-1.5 pl-4"
            style="background: var(--c-bg-elevated)"
        >
            <div
                class="min-w-0 flex-1 overflow-hidden text-[14px] font-medium text-ellipsis whitespace-nowrap"
                style="color: var(--c-fg1); font-family: var(--c-font-mono)"
            >
                {{ props.link }}
            </div>
            <button
                class="inline-flex h-9 items-center gap-1.5 rounded-[9px] bg-white px-3.5 text-[13px] font-semibold"
                style="
                    color: var(--c-fg1);
                    box-shadow:
                        0 1px 2px rgba(0, 0, 0, 0.06),
                        0 0 0 0.5px rgba(0, 0, 0, 0.04);
                "
                @click="copy"
            >
                <template v-if="copied">
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="var(--c-success)"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <path d="M5 12l5 5 9-11" />
                    </svg>
                    Скопировано
                </template>
                <template v-else>
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <rect x="9" y="9" width="11" height="11" rx="2" />
                        <rect x="4" y="4" width="11" height="11" rx="2" />
                    </svg>
                    Копировать
                </template>
            </button>
        </div>

        <div
            v-if="!active"
            class="flex gap-2.5 rounded-xl px-3.5 py-3 text-[12px] leading-[1.45]"
            style="background: var(--c-warning-bg); color: #8c5400"
        >
            <svg
                class="shrink-0"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
            >
                <circle cx="12" cy="12" r="9" />
                <path d="M12 8v.01M12 11v5" />
            </svg>
            <span>
                У вас нет активных пакетов. Линия временно недоступна —
                приглашённые не смогут зарегистрироваться по этой ссылке.
                Активируйте любой уровень, чтобы возобновить работу.
            </span>
        </div>
    </div>
</template>

// ui_kits/partner/RefLinkCard.jsx
const refStyles = {
  wrap: {
    background: '#fff', borderRadius: 20, padding: '22px 24px',
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    display: 'flex', flexDirection: 'column', gap: 16,
  },
  head: { display: 'flex', alignItems: 'center', gap: 12 },
  title: { fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 600, letterSpacing: '-0.01em' },
  status: (active) => ({
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '3px 9px', borderRadius: 999,
    fontSize: 11, fontWeight: 600,
    background: active ? 'var(--success-bg)' : 'var(--neutral-bg)',
    color: active ? '#1a6e34' : 'var(--fg2)',
    marginLeft: 'auto',
  }),
  dot: (active) => ({ width: 6, height: 6, borderRadius: '50%', background: active ? 'var(--success)' : 'var(--neutral)' }),

  field: {
    display: 'flex', alignItems: 'center', gap: 10,
    height: 48, padding: '0 6px 0 16px',
    background: 'var(--bg-elevated)',
    borderRadius: 12,
  },
  link: {
    flex: 1, minWidth: 0,
    fontFamily: 'var(--font-mono)', fontSize: 14, color: 'var(--fg1)',
    fontWeight: 500,
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  copyBtn: {
    height: 36, padding: '0 14px',
    background: '#fff', border: 0, borderRadius: 9,
    fontSize: 13, fontWeight: 600, color: 'var(--fg1)',
    cursor: 'pointer', fontFamily: 'inherit',
    display: 'inline-flex', alignItems: 'center', gap: 6,
    boxShadow: '0 1px 2px rgba(0,0,0,0.06), 0 0 0 0.5px rgba(0,0,0,0.04)',
  },

  notice: {
    display: 'flex', gap: 10, padding: '12px 14px',
    background: 'var(--warning-bg)', borderRadius: 12,
    color: '#8c5400', fontSize: 12, lineHeight: 1.45,
  },
};

function RefLinkCard({ active = true }) {
  const [copied, setCopied] = React.useState(false);
  const link = 'cascade.app/r/481923';

  const copy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 1400);
  };

  return (
    <div style={refStyles.wrap}>
      <div style={refStyles.head}>
        <div style={refStyles.title}>Реферальная ссылка</div>
        <div style={refStyles.status(active)}>
          <span style={refStyles.dot(active)}/>
          {active ? 'Активна' : 'Неактивна'}
        </div>
      </div>

      <div style={refStyles.field}>
        <div style={refStyles.link}>{link}</div>
        <button style={refStyles.copyBtn} onClick={copy}>
          {copied ? <><IcCheck size={14} stroke="var(--success)"/> Скопировано</> : <><IcCopy size={14}/> Копировать</>}
        </button>
      </div>

      {!active && (
        <div style={refStyles.notice}>
          <IcInfo size={14}/>
          <span>
            У вас нет активных пакетов. Линия временно недоступна — приглашённые не смогут зарегистрироваться по этой ссылке. Активируйте любой уровень, чтобы возобновить работу.
          </span>
        </div>
      )}
    </div>
  );
}

Object.assign(window, { RefLinkCard });
