// ui_kits/partner/InvitesTable.jsx
const invitesStyles = {
  wrap: {
    background: '#fff', borderRadius: 18,
    boxShadow: '0 1px 0 rgba(0,0,0,0.04)',
    overflow: 'hidden',
  },
  head: {
    padding: '18px 24px 14px',
    display: 'flex', alignItems: 'baseline', gap: 12,
  },
  title: { fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 600, letterSpacing: '-0.01em' },
  sub: { fontSize: 12, color: 'var(--fg3)' },

  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    fontSize: 11, color: 'var(--fg3)', fontWeight: 600,
    textTransform: 'uppercase', letterSpacing: '0.04em',
    padding: '12px 24px', textAlign: 'left',
    borderTop: '1px solid var(--hairline)',
    borderBottom: '1px solid var(--hairline)',
    background: 'var(--bg)',
  },
  td: {
    padding: '14px 24px',
    borderBottom: '1px solid var(--hairline-soft)',
    fontSize: 13, color: 'var(--fg1)',
  },
  user: { display: 'flex', alignItems: 'center', gap: 10 },
  avatar: (hue) => ({
    width: 28, height: 28, borderRadius: '50%',
    background: `linear-gradient(135deg, hsl(${hue}, 70%, 70%), hsl(${(hue + 30) % 360}, 70%, 55%))`,
    color: '#fff', fontWeight: 600, fontSize: 11,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  }),
  pill: (variant) => {
    const map = {
      active:  ['var(--success-bg)', '#1a6e34', 'var(--success)'],
      grey:    ['var(--neutral-bg)', 'var(--fg2)', 'var(--neutral)'],
      empty:   ['var(--bg-elevated)', 'var(--fg3)', 'var(--fg3)'],
    };
    const [bg, fg, dot] = map[variant];
    return { bg, fg, dot };
  },
  pillNode: (v) => ({
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '3px 9px', borderRadius: 999,
    fontSize: 11, fontWeight: 600,
    background: v.bg, color: v.fg,
  }),
};

const INVITES = [
  { user: 'u_4821', level: 'Level 2',  earned: '60,00',  joined: '5 дн назад', status: 'active' },
  { user: 'u_9182', level: 'Level 1',  earned: '12,00',  joined: '5 дн назад', status: 'active' },
  { user: 'u_3019', level: 'Level 2',  earned: '60,00',  joined: '8 дн назад', status: 'active' },
  { user: 'u_7702', level: 'Level 4',  earned: '0,00',   joined: '2 нед назад', status: 'grey' },
  { user: 'u_5512', level: 'не куплен', earned: '0,00',   joined: '3 нед назад', status: 'empty' },
];

const STATUS_LABEL = { active: 'Активен', grey: 'Неактивен в очереди', empty: 'Не активирован' };

function InvitesTable() {
  return (
    <div style={invitesStyles.wrap}>
      <div style={invitesStyles.head}>
        <div style={invitesStyles.title}>Приглашённые</div>
        <div style={invitesStyles.sub}>5 рефералов · 3 активных</div>
      </div>
      <table style={invitesStyles.table}>
        <thead>
          <tr>
            <th style={invitesStyles.th}>Пользователь</th>
            <th style={invitesStyles.th}>Уровень</th>
            <th style={invitesStyles.th}>Заработано вами</th>
            <th style={invitesStyles.th}>Присоединился</th>
            <th style={invitesStyles.th}>Статус</th>
          </tr>
        </thead>
        <tbody>
          {INVITES.map((r, i) => {
            const v = invitesStyles.pill(r.status);
            const hue = (i * 67) % 360;
            return (
              <tr key={r.user}>
                <td style={invitesStyles.td}>
                  <div style={invitesStyles.user}>
                    <div style={invitesStyles.avatar(hue)}>{r.user.slice(2,4).toUpperCase()}</div>
                    <span style={{ fontFamily: 'var(--font-mono)' }}>{r.user}</span>
                  </div>
                </td>
                <td style={invitesStyles.td}>{r.level}</td>
                <td style={{...invitesStyles.td, fontFamily: 'var(--font-mono)', fontWeight: 600, fontVariantNumeric: 'tabular-nums'}}>+{r.earned} USDT</td>
                <td style={{...invitesStyles.td, color: 'var(--fg2)'}}>{r.joined}</td>
                <td style={invitesStyles.td}>
                  <span style={invitesStyles.pillNode(v)}>
                    <span style={{ width: 6, height: 6, borderRadius: '50%', background: v.dot }}/>
                    {STATUS_LABEL[r.status]}
                  </span>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

Object.assign(window, { InvitesTable });

// resources/js/components/cascade/partner/InvitesTable.vue
<script setup lang="ts">
import { computed } from 'vue';

type InviteStatus = 'active' | 'grey' | 'empty';

interface Partner {
    id: number;
    name: string;
    level: number | null;
    earned: number;
    joined: string;
    active: boolean;
}

interface Invite {
    user: string;
    level: string;
    earned: string;
    joined: string;
    status: InviteStatus;
}

const props = withDefaults(
    defineProps<{
        partners?: Partner[];
        partnersCount?: number;
        activeCount?: number;
    }>(),
    { partners: () => [], partnersCount: 0, activeCount: 0 },
);

const invites = computed<Invite[]>(() =>
    props.partners.map((p) => ({
        user: 'u_' + p.id,
        level: p.level !== null ? 'Level ' + p.level : 'не куплен',
        earned: p.earned.toLocaleString('ru-RU', { minimumFractionDigits: 2, maximumFractionDigits: 2 }),
        joined: p.joined,
        status: p.active ? 'active' : p.level !== null ? 'grey' : 'empty',
    })),
);

const statusLabel: Record<InviteStatus, string> = {
    active: 'Активен',
    grey: 'Неактивен в очереди',
    empty: 'Не активирован',
};

const pillStyle: Record<InviteStatus, { bg: string; fg: string; dot: string }> =
    {
        active: {
            bg: 'var(--c-success-bg)',
            fg: '#1a6e34',
            dot: 'var(--c-success)',
        },
        grey: {
            bg: 'var(--c-neutral-bg)',
            fg: 'var(--c-fg2)',
            dot: 'var(--c-neutral)',
        },
        empty: {
            bg: 'var(--c-bg-elevated)',
            fg: 'var(--c-fg3)',
            dot: 'var(--c-fg3)',
        },
    };

function avatarStyle(hue: number): Record<string, string> {
    return {
        background: `linear-gradient(135deg, hsl(${hue}, 70%, 70%), hsl(${(hue + 30) % 360}, 70%, 55%))`,
    };
}

function initials(user: string): string {
    return user.slice(2, 4).toUpperCase();
}
</script>

<template>
    <div
        class="overflow-hidden rounded-[18px] bg-white"
        style="box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04)"
    >
        <div class="flex items-baseline gap-3 px-6 pt-[18px] pb-3.5">
            <div
                class="text-[18px] font-semibold tracking-[-0.01em]"
                style="color: var(--c-fg1); font-family: var(--c-font-display)"
            >
                Приглашённые
            </div>
            <div class="text-[12px]" style="color: var(--c-fg3)">
                {{ props.partnersCount }} рефералов · {{ props.activeCount }} активных
            </div>
        </div>

        <table class="w-full border-collapse">
            <thead>
                <tr>
                    <th
                        v-for="th in [
                            'Пользователь',
                            'Уровень',
                            'Заработано вами',
                            'Присоединился',
                            'Статус',
                        ]"
                        :key="th"
                        class="px-6 py-3 text-left text-[11px] font-semibold tracking-[0.04em] uppercase"
                        style="
                            color: var(--c-fg3);
                            background: var(--c-bg);
                            border-top: 1px solid var(--c-hairline);
                            border-bottom: 1px solid var(--c-hairline);
                        "
                    >
                        {{ th }}
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(row, i) in invites" :key="i">
                    <td
                        class="px-6 py-3.5 text-[13px]"
                        style="
                            color: var(--c-fg1);
                            border-bottom: 1px solid var(--c-hairline-soft);
                        "
                    >
                        <div class="flex items-center gap-2.5">
                            <div
                                class="flex h-7 w-7 items-center justify-center rounded-full text-[11px] font-semibold text-white"
                                :style="avatarStyle((i * 67) % 360)"
                            >
                                {{ initials(row.user) }}
                            </div>
                            <span style="font-family: var(--c-font-mono)">{{
                                row.user
                            }}</span>
                        </div>
                    </td>
                    <td
                        class="px-6 py-3.5 text-[13px]"
                        style="
                            color: var(--c-fg1);
                            border-bottom: 1px solid var(--c-hairline-soft);
                        "
                    >
                        {{ row.level }}
                    </td>
                    <td
                        class="px-6 py-3.5 text-[13px] font-semibold"
                        style="
                            color: var(--c-fg1);
                            font-family: var(--c-font-mono);
                            font-variant-numeric: tabular-nums;
                            border-bottom: 1px solid var(--c-hairline-soft);
                        "
                    >
                        +{{ row.earned }} USDT
                    </td>
                    <td
                        class="px-6 py-3.5 text-[13px]"
                        style="
                            color: var(--c-fg2);
                            border-bottom: 1px solid var(--c-hairline-soft);
                        "
                    >
                        {{ row.joined }}
                    </td>
                    <td
                        class="px-6 py-3.5 text-[13px]"
                        style="
                            color: var(--c-fg1);
                            border-bottom: 1px solid var(--c-hairline-soft);
                        "
                    >
                        <span
                            class="inline-flex items-center gap-1.5 rounded-full px-[9px] py-[3px] text-[11px] font-semibold"
                            :style="{
                                background: pillStyle[row.status].bg,
                                color: pillStyle[row.status].fg,
                            }"
                        >
                            <span
                                class="h-1.5 w-1.5 rounded-full"
                                :style="{
                                    background: pillStyle[row.status].dot,
                                }"
                            />
                            {{ statusLabel[row.status] }}
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>
